### ISSUE TITLE
Port SAMOA  to Gearpump

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1007]
Sub steps:

- [x] . study SAMOA of its usage
- [x] run SAMOA over Storm, and prepare an actual example
- [x] Port SAMOA to Gearpump, and prepare a demo.
- [ ] final delivery: PR, experiment module.

**Comment by clockfly** [comment]
This depends on 

1. Dag with loop
2. task emit Direct

**Comment by manuzhang** [comment]
PR is ready at https://github.com/apache/incubator-samoa/pull/54

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-60
