### ISSUE TITLE
transfer "Any" in messages

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1018]
Continuing the discussion in #836, `Message` now allows `AnyRef`to be transferred, since kryo needs to know the class name to serialize the Message.

```scala
case class Message(msg: AnyRef, timestamp: TimeStamp = Message.noTimeStamp)
```

After some experiment, I found Kryo is able to serialize  `AnyVal`s that can be unboxed into Java primitives with `DefaultSerializer`. One exception I'm aware of is `BoxedUnit``()`, which needs user to configure like other `AnyRef`s which haven't been registered. 

Hence, I propose we allow transferring `Any` in messages.

**Comment by clockfly** [comment]
In java, it will do automatic boxing.

In scala, you can do manual boxing like this:
Message(3.asInstanceOf[AnyRef], ..

**Comment by clockfly** [comment]
update doc in http://www.gearpump.io/site/0.6/how_to_write_a_streaming_application/#about-message-type

**Comment by huafengw** [comment]
@Renkai raised the question again.
> With type Any we don't need to cast basic scala types like Int,Long,Double, and Any seems well compatible with java.
> I tried Any,java will treat Any as Object,too.
