### ISSUE TITLE
Provide a Spark Streaming compatible DSL

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump#1052]
As spark is extremely popular today, I think it will beneficial to support some kind of integration between Spark and Gearpump. One direction is to provide a Spark Streaming compatible DSL that can be used to replace Spark Streaming with Gearpump. So that, we can use Gearpump as a low-latency replacement for Spark Streaming but keep the interoperability between Gearpump and Spark batch.

Just a rough idea. No detailed study made yet.

In this model, Gearpump and Spark cluster are running in parallel. User's Spark Streaming application submitted to Gearpump will be translated to Gearpump DSL and running on Gearpump.

The command "gear --spark spark_streaming_app.jar" will perform the client side rewrite for this jar to replace Spark Streaming DSL with corresponding Gearpump DSL. So, basically user is transparent. But Gearpump DSL shall be highly compatible with Spark Streaming DSL to simplify the   rewrite.

**Comment by kkasravi** [comment]
It looks like we are aligning GP DSL to work with both akka-streams and apache beam. Since spark also runs under apache beam I think our DSL efforts are focused on these 2 frameworks. @whjiang please reopen if you think we should have specific focus on the spark DSL.
