### ISSUE TITLE
When possible remove .sbtopts and jvm.sbt

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1180]
We have two special config file for sbt build in a CI environment. But they might be not suitable for local development environment. For instance `-J-XX:MaxPermSize=512m` is deprecated in JDK8. The setting of `jvm.sbt` seems never effective. If the CI-system supports environment variables, I'd suggest to document this in readme and define them as environment variables.

**Comment by clockfly** [comment]
I removed XX:MaxPermSize

close this.
