### ISSUE TITLE
Add graph cycle detection to avoid submitting a dag with cycle

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1194]

**Comment by huafengw** [comment]
Why we do not support cycle? From the task message transport layer, it actually works well I think.

**Comment by clockfly** [comment]
The min-clock is defined recursively. The clock will not be tracked correctly.

**Comment by clockfly** [comment]
demo code for cycle detection:
https://github.com/jgrapht/jgrapht/wiki/DependencyDemo

**Comment by huafengw** [comment]
The Graph#vertexHierarchyLevelMap will loop infinitely if the graph has a loop.
