### ISSUE TITLE
once an application is killed, it should be restartable

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1207]
[Story](https://www.pivotaltracker.com/story/show/99782098)
the UI shows the application is inactive but the restart button is missing

**Comment by clockfly** [comment]
When an application is killed. We need to clean up the resource in master. 
Currently, we store a lot of application data in master memory.

I think this case can be implemented after we introduce the distributed persistence storage for master node, so that we don't need to consume too much memory.

**Comment by kkasravi** [comment]
@clockfly @stanleyxu2005 
For this it actually refers to the lack of a restart button after the application is killed and becomes inactive.  Purely a UI issue. Since we already allow restart for a running application it seems like this feature can be implemented to restart an inactive application. This is why i assigned to Stanley.

**Comment by stanleyxu2005** [comment]
Hmm. Once application is restarted, the application id will be changed. This is not a *normal* restart operation.

**Comment by kkasravi** [comment]
@stanleyxu2005 
You could for example do what is done when it's running - leave the current entry/row as inactive and launch a new application. The difference being you do not kill the application (since it's already inactive).

**Comment by stanleyxu2005** [comment]
One problem is that there is no api to retrieve basic information of an inactive application. Imagine that user reload the page `http://dashboard:8090/#/apps/streamingapp/1`, nothing can be shown. I regard this missing api as a blocking issue for ui.

**Comment by stanleyxu2005** [comment]
According to the discussion thread, the issue is blocked by storage feature #1822

**Comment by manuzhang** [comment]
I wonder whether we can store the information at client side. Think about Bash where we can press the "up" button to look for previous commands. They are gone if we close the terminal. Restarting an application is like pressing that "up" button.

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-97
