### ISSUE TITLE
Support DAG with loops

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1231]
DAG with loop should not be called DAG :)

We see use cases that require a feedback channel. 
The challengues will be:
1. how to support the low watermark clock? As the clock is defined recursively?
2. How to support back-pressure. DAG with loop can possiblely create a live-lock issue. With each processor wait for acks from other processor before sending acks.

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-78
