### ISSUE TITLE
Build nightly end-to-end scenario test set to better find regressions

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1243]
We need a system way to assure quality for each release tag.

**Comment by clockfly** [comment]
Requirements:

end to end test. Which means we should cover all use cases a normal user may encounter. 

1. support gearpump to yarn cluster. 
2. read/write data from/to kafka.
3. Submit/kill/query all built-in examples from command line shell.
4. Submit/kill examples all built-in example from UI.
5. message loss. Machine crash, High availability test.
6. performance regression test.
7. able to run storm-benchmark over gearpump.
8. The conf is effective.
9. all commands under bin/ can run correctly.

**Comment by stanleyxu2005** [comment]
Here is a [proposal](https://gist.github.com/stanleyxu2005/ba71de4947bae11aa77c)
