### ISSUE TITLE
incorrect info on processor tab when changing dags on dashboard

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1266]
1. if an upstream processor is changed, the input parallelism of downstream processor will be the accumulated value of all previous and existing upstream processor numbers.
2. so is the executor path.

**Comment by stanleyxu2005** [comment]
Where to see the incorrect information? More clue is required.

**Comment by manuzhang** [comment]
InputProcessor of SOLStreamProcessor accumulates to 2 after changing SOLStreamProducer

![snip20150901_1](https://cloud.githubusercontent.com/assets/1191767/9595630/4e101082-509b-11e5-810f-4582b6a8f789.png)
