### ISSUE TITLE
Rename http://github.com/intel-data/gearpump to https://github.com/gearpump/gearpump

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1303]
[Story](https://www.pivotaltracker.com/story/show/100779100)
Rather than fork the repo - remove the fork and rename - see https://github.com/blog/1508-repository-redirects-are-here

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
@whjiang  @huafengw  @manuzhang  @TomaszT  @stanleyxu2005 

What is your opinion?

Looks like Kam has found a way to transfer the project, while reserving all watcher/stars, all issues, and all commit history.

The advantage will be that we can group all geaprump related project under account github.com/gearpump.

**Comment by huafengw** [comment]
+1

**Comment by clockfly** [comment]
And it will do automatic redirect.

When you access github.com/intel-hadoop/gearpump, it will automatically redirect to github.com/gearpump/gearpump

**Comment by stanleyxu2005** [comment]
+1

**Comment by manuzhang** [comment]
+1

**Comment by kkasravi** [comment]
Sean should probably do the move - so delete fork, move intel-hadoop/gearpump.We do not want it failing due to lack of permissions.  


     On Thursday, August 6, 2015 10:59 PM, ManuZhang <notifications@github.com> wrote:
   

 +1—

**Comment by clockfly** [comment]
OK, @whjiang  @TomaszT 

Please comment

**Comment by whjiang** [comment]
+1.

**Comment by clockfly** [comment]
close this.
