### ISSUE TITLE
Fail to submit an application from frontend UI when setting a different version HDFS as jarStore

### ISSUE THREAD

**Issue by skw1992** [gearpump/gearpump#1346]
Fail to set HDFS as jarStore in Linux cluster, for the hadoop server version is different from the client version

**Comment by whjiang** [comment]
This issue is caused because currently Client and Server use their own JarStoreService to upload/download Jar files. Thus, if the HDFS version is not compatible, we will lead to this problem.

**Comment by whjiang** [comment]
A solution to this problem is change the flow how a JAR is uploaded. 

Currently, jar is uploaded via this flow:

For local jar store
```
1. client ask master for the file server address
2. client upload file to file server, and file server persist to master local directory.
3. worker download file from file server.
```

For DFS jar store
```
1. client upload file directly to DFS directory
2. worker download file from DFS directory
```

The solution to avoid current problem and also eliminate the hadoop dependency at client side #1244 is using following flow:
```
1. client ask master for the file server address
2. client upload file to file server, and file server persist to configured master local or HDFS directory.
3. worker download file from master local directory (via file server) or HDFS directory.
```

**Comment by whjiang** [comment]
The benefits of this new design:
1. it fixes issue like HDFS version compatibility.
2. client no longer needs to incorporate hadoop package as dependency if server configures to use DFSJarStore. (In current code, it is quite weird that which packages client depends depends on how the server is configured. Generally, I believe such server configuration shall be hidden from Client).
3. fix Jar store permission issue. Currently, for DFSJarStore, client and server write/read HDFS independently. So if client uses different username than server, there will be permission issue, which is a little tougher in Kerberos environment.

**Comment by whjiang** [comment]
And addition to above design, I also plan to add `appId` into jar upload. So that, jar store knows which application this jar belongs to. Currently, we have no way to perform application lifecycle management. Thus, no jar clean up at all. With appId included, we can manage jars by managing applications.

**Comment by whjiang** [comment]
One blocker one is `submitdag` REST API  (#1450) which doesn't have appId in it. With #1450 fixed, this work can go on quickly. I have most of the code ready.

**Comment by huafengw** [comment]
The current problem is that the classpath of dashboard does not contain hadoop libraries.

Migrated to https://issues.apache.org/jira/browse/GEARPUMP-64
