### ISSUE TITLE
Split metrics owner name and metrics name

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1359]
Currently its inconvenience for dashboard to handle metrics name. The metric owner name and real metric name are mixed together. For instance, `worker0.executor1.physical.memory.total`, Dashboard will have to split the string to understand it is a  `physical.memory.total`. 

Better split them where it is manipulated, so that dashboard do not need to parse the name everything.

**Comment by clockfly** [comment]
Change to P3

**Comment by clockfly** [comment]
@stanleyxu2005 

This is designed like this. For all the metrics, they should also can be rendered by third party metrics visualition tool, like Graphite. 

The metric name is the only clue to differentiate metrics from two metrics source.
