### ISSUE TITLE
Pass config when replacing a processor

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1366]
Suppose the new processor will need some configuration when initiating, user can not provide config from the frontend.

*Update 1*: The config is actually a string to string map, not a config file.

**Comment by manuzhang** [comment]
What if the user config value is not String ? What if user needs to do some operation on the config value before submitting the result ?

**Comment by stanleyxu2005** [comment]
@manuzhang I was told user config is a list of java options.... like `-Dfoo1=bar1 -Dfoo2=bar2`

**Comment by huafengw** [comment]
@stanleyxu2005 actually it's not. For simplicity, my expectation is support string configurations first, which just like java options.

**Comment by huafengw** [comment]
Migrated to https://issues.apache.org/jira/browse/GEARPUMP-59
