### ISSUE TITLE
Dashboard cannot be open when Services bound to the same IPv6 address as an IPv4 address taken by another process

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1375]
As in the following output from `lsof -i -P | grep -i "listen"`, 36866 is launched first and takes 8090 (IPv4). Then our `Services` is launched and bound to the same 8090 port (IPv6). User cannot browse to "127.0.0.1:8090" for UI since (my guess) the http request is forwarded to 36866 and there is no other error info. 

```
36866 doria    9u  IPv4 0x9df0188bb3912af1      0t0  TCP *:8090 (LISTEN)
37935 doria  111u  IPv6 0x9df0188bb422c321      0t0  TCP localhost:61673 (LISTEN)
37935 doria  125u  IPv6 0x9df0188bb23a9781      0t0  TCP *:8091 (LISTEN)
37935 doria  126u  IPv6 0x9df0188bb03a1781      0t0  TCP *:8090 (LISTEN)
```

**Comment by clockfly** [comment]
Can you document this in FAQ on the web site?
