### ISSUE TITLE
allow user to output to a specific subscriber

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1377]
Currently, message from a task is output to all its subscribers but a user may want to send some messages to one of the subscribers while other messages to another. The different subscribers could end up as the same Processor through different Partitioners.

Hence, I'm considering allowing user to `output` to a specific processor / subscriber with `output("b", "p1", message)` or `output("c", "p2", message)` where 

```scala
  val a = Processor[A]("a", 1)
  val b = Processor[B]("b", 1)
  val c = Processor[C]("c", 1)
  val p1 = Partitioner[P1]("p1")
  val p2 = Partitioner[P2]("p2")

  val graph = Graph(a ~ p1 ~> b, a ~ p2 ~> c)
```

"a", "b", "c", "p1" and "p2" are globally unique ids to identify processors and partitioners respectively.

Just my immature thoughts to open further discussions.

**Comment by kkasravi** [comment]
Do you think there is benefit in typing output even if inferred? EG output[T:ClassTag]

**Comment by manuzhang** [comment]
by T you mean the class type of a Processor ?

**Comment by clockfly** [comment]
I think we need to think whether the strong binding here will impact feature "dynamic dag".

**Comment by manuzhang** [comment]
superseded by #1456
