### ISSUE TITLE
cross-build not enabled for release tag

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1395]
latest version is not published to repo
https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/

There is error when doing the publish

```
signature-staging
failureMessage	Missing Signature: '/com/github/intel-hadoop/gearpump-core_2.10/0.4.3/gearpump-core_2.10-0.4.3-tests-javadoc.jar.asc' does not exist for 'gearpump-core_2.10-0.4.3-tests-javadoc.jar'.
```

Looks like we have not signed the 2.10 cross-build. 

Maybe we missed the "+" when sign the jar file?
check:
https://libraries.io/github/realestate-com-au/pact-jvm-provider-spring-mvc

**Comment by clockfly** [comment]
+publishSigned

**Comment by clockfly** [comment]
https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/gearpump-core_2.11/

Still not published

**Comment by clockfly** [comment]
version is wrong
https://github.com/gearpump/gearpump/blob/0.6.1.3/version.sbt

**Comment by manuzhang** [comment]
https://oss.sonatype.org/content/repositories/releases/com/github/intel-hadoop/

**Comment by clockfly** [comment]
website gearpump.io not updated.

**Comment by manuzhang** [comment]
done
