### ISSUE TITLE
would it better to support on external KafkaSink to support single Array[Byte] rather than (Array[Byte], Array[Byte])

### ISSUE THREAD

**Issue by kris21he** [gearpump/gearpump#1397]
I have to make my sink source message format to tuple2(Array[Byte], Array[Byte]) 
if not match that format, it would throw class cast exception in backend.
but it would be better just support Array[Byte] and then serialize it to an Object?

**Comment by manuzhang** [comment]
thanks for your advice. I've opened #1398 to account for both cases.
