### ISSUE TITLE
incorrect Executor.TaskCount on Application overview tab

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1399]
To reproduce, please launch a local SOL application with args `-streamProducer 3 -streamProcessor 3`. Usually, executor 1 and executor 2 will only have 1 or 2 tasks instead of 3.

**Comment by stanleyxu2005** [comment]
Eventually it is a backend issue. 

I've queried `/api/v1.0/appmaster/3/executor/1`, which expects task count to be 2. But see the restapi response below, the task count is 3.

```
{"id":1,"workerId":0,"actorPath":"akka.tcp://app3system1@127.0.0.1:40228/remote/akka.tcp/app3-executor-1@127.0.0.1:48006/user/daemon/appdaemon3/$c/appmaster/executors/1","logFile":"/dev/shm/proj/gearpump/output/target/pack/logs","status":"active","taskCount":3,"tasks":[[1,[{"processorId":1,"index":0}]],[0,[{"processorId":0,"index":1},{"processorId":0,"index":0}]]],"jvmName":"139842@node22"}
```

**Comment by stanleyxu2005** [comment]
See also #1401
