### ISSUE TITLE
Executor for dead processor is still alive?

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1401]
While troubleshooting #1399, we found the the application (also in worker section) will return all executors, including those work for dead processors. Actually, dead processor stops processing any new messages, but the process is still alive. 

It needs to be distinguish the following things in the dashboard:
1. The processor page is still accessible by typing url? (considering yes, and provide links in a new history page)
2. The impacted executors should still appear in executor list table (in application overview)? (considering no. The backend should consider how to define the status of such an executor. Currently it is still `running`.)
3. The executors should still appear in worker page? (considering yes but with a grey indicator color. Currently the worker does have executor status information.)

**Comment by clockfly** [comment]
@stanleyxu2005 

This is related with dynamic-dag. 
1. Sometimes user still want to query the in-memory state of processor that has been repalced. That is why we don't shutdown it down.
2. another reason is that it is tricky to handle the recovery when we want to recover to state of old DAG(before dag replacement)

Maybe We can make that configurable(whether to shut down old dag processor that has been replaced).

**Comment by manuzhang** [comment]
The problem is when user sum up the `Executor.TaskCount` they find the number is not consistent with that on the overview tab. We could explicitly display counts for **both live and dead tasks** on the overview tab such that users won't be confused.

**Comment by manuzhang** [comment]
I also find that executors that have been shutdown are still displayed on the application overview page. Is this expected ?

**Comment by stanleyxu2005** [comment]
So we need to a filter to switch active/all executors

**Comment by stanleyxu2005** [comment]
@manuzhang A simplified solution can be: When a processor is replaced, we add a "replaced" flag to this processors, so that we are able to distinguish such processor with normal processors.

**Comment by manuzhang** [comment]
It's actually new processors and processor id is different and users don't know which processors have been replaced from dashboard.  I'm not sure whether it conveys right information to users. And what about executors ?

**Comment by manuzhang** [comment]
I guess sometime we would allow users to query history dag versions from a pull-down menu and they get all the statistics (average throughput, average latency, etc) of that dag version. Well, that's just off top of my head. What I mean is that we not only solve the problem for now, we'd better have a blueprint to account for future usages.

**Comment by stanleyxu2005** [comment]
I marked dead processors with a gray stripe at the left side of processor table in [this PR](https://github.com/gearpump/gearpump/pull/1765). Close the issue.
