### ISSUE TITLE
It take too long for UI metrics chart to display

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1411]
How to reproduce:
1. submit the application jar by UI
2. Switch to application view
3. Check the charts, it take a long time to display the metrics. (Maybe > 10 seconds?)

**Comment by stanleyxu2005** [comment]
No. The fetch interval is 30 seconds. This not a bug IMO.

**Comment by clockfly** [comment]
Yes, maybe improvement is better word here.

When start the APP, there is NO UI charts showing. It make me feels that something goes wrong.

At the same time, there is a number under the metric chart title(like xxx message/second) and that number is changing! but the line chart is not!

I think it is better to show something line charts as soon as we display the above mentioned number.

**Comment by stanleyxu2005** [comment]
Even we have one data point on chart, you will still wait another 30 seconds to see the 2nd (maybe also the 3rd) points. It looks as confusing as "No Graph Data Available".

**Comment by clockfly** [comment]
@stanleyxu2005 

That is exactly I want to say. We need to improve this, so that user don't feel confused.

**Comment by manuzhang** [comment]
![snip20150915_2](https://cloud.githubusercontent.com/assets/1191767/9866637/3797f944-5b97-11e5-8194-3fc4dd605081.png)

**Comment by stanleyxu2005** [comment]
This is not wrong. The throughput values above chart will be updated every 2 seconds, if there is new value from backend.

The recent change does the following things:
1. Up time will have a viable unit. E.g. the app runs 30 secs, it shows 30 secs. It it runs 20 hours and 5 mins, it shows 20 hours.
2. The historical chart will show data every 15 seconds. It will show at most 15 minutes data.

**Comment by manuzhang** [comment]
Not sure what you mean but I agree with @clockfly on what we should achieve

> I think it is better to show something line charts as soon as we display the above mentioned number.

**Comment by stanleyxu2005** [comment]
Yes. I do believe there is improvement potential.

**Comment by stanleyxu2005** [comment]
I have an idea: assuming the chart update interval is 15 seconds. In the first 15 seconds, the chart will show a loading message "Gathering data...". After that it will show the recent 60 points (15 min). Historical data will be shown in historical view.

**Comment by stanleyxu2005** [comment]
The commit dea16a1 brings huge performance improvement. Querying 2000 tasks of a word count application does not make any stress to browser.

**Comment by stanleyxu2005** [comment]
![processor_metrics](https://cloud.githubusercontent.com/assets/5162687/12005809/11d954b2-abf3-11e5-9b1a-202cdfb6863d.png)

![task_metrics](https://cloud.githubusercontent.com/assets/5162687/12005811/17ac22fc-abf3-11e5-9f72-cf37eacbb9b7.png)
