### ISSUE TITLE
error info is not prompted in UI when submission failed

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1423]
![ui_improve](https://cloud.githubusercontent.com/assets/2595532/9867104/8e04a318-5b9c-11e5-8407-fa04145afea4.jpg)

**Comment by stanleyxu2005** [comment]
![1](https://cloud.githubusercontent.com/assets/5162687/9934748/c948e64c-5d85-11e5-96c7-94ac190e5e63.png)
New dialog will show error message as a tooltip.

**Comment by stanleyxu2005** [comment]
There are still some glitches:
1. The filter text in file upload dialog is incorrect
2. If the error has a long stack trace, tooltip is not suitable. A popup window with full stack trace would be better.
3. The submit button has a couple of pixel more at left side.

**Comment by stanleyxu2005** [comment]
![1](https://cloud.githubusercontent.com/assets/5162687/9937698/5c136cdc-5d94-11e5-8865-ddabd2e66782.png)
This is how it looks with the new PR
