### ISSUE TITLE
DistributedShell example cannot be submitted

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1434]
[Story](https://www.pivotaltracker.com/story/show/103517490)
DistributedShell example fails to submit. No details are provided as to why

**Comment by clockfly** [comment]
missing Main class.

**Comment by clockfly** [comment]
duplicate of #1423

**Comment by stanleyxu2005** [comment]
Now you can see the error message, when uploaded jar is rejected by the server. #1435
