### ISSUE TITLE
Should validate uploaded JAR

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1437]
I have launched a word count example and then I replaced the split processor with an invalid one (I use slf-log4j.jar). I found several issues:

1. There is no error message from backend, even when the specified task class is not found on class path.
2. As there is no data sent from the *broken* processor, after couple of seconds, the send throughput will decrease to zero. The number of total sent messages will be 0. Actually the count of previous split processor is not taken into account.
3. The application clock becomes `9223372036854775807`. The application status is still `active`.

**Comment by huafengw** [comment]
It's kind of hard to return the error message when replacing the processor. There is a rest api ```api/v1.0/appmaster/0/errors``` which will return the last error message of the application. Is it acceptable using this api to return the ClassNotFoundException?

**Comment by stanleyxu2005** [comment]
I mean, when we write user application, we need at least a minimal interface, so that when we have an uploaded jar, we know what classes the JAR provides, what classpaths the JAR needs, etc. 

For instance:
```
String getDescription();
Set[String] getDependencies();
Set[String] getTaskClasses();
Set[String] getPartitioners();
```

**Comment by kkasravi** [comment]
I think we'll need a new type of POST similar to SubmitApplicationRequest but perhaps more like ModifyDAGRequest. the description, dependencies, tasks and partitioners should be included in the jar manifest. See #1455 - the REST endpoint would first validate the JSON schema, then validate the tasks, etc.

**Comment by whjiang** [comment]
> I mean, when we write user application, we need at least a minimal interface, so that when we have an uploaded jar, we know what classes the JAR provides, what classpaths the JAR needs, etc. For instance:
> 
> String getDescription();
> Set[String] getDependencies();
> Set[String] getTaskClasses();
> Set[String] getPartitioners();

Hi @stanleyxu2005, if you only needs to find the classes derived from ```Task```, you can use some utility to find all the classes derived from ```Task```. But if you are looking for things like processor definition, description, dependencies. Then, we need some design here.

**Comment by stanleyxu2005** [comment]
@whjiang The validation happens at backend, so we need to extract information like processor definition, description, dependencies. Yes we need a design. And the information is used for validation, but it can be shared by other use cases later.

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-96
