### ISSUE TITLE
Unable to run master with ip and port args

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1447]
[Story](https://www.pivotaltracker.com/story/show/104270502)
Master will exit if command args do not agree with config

**Comment by kkasravi** [comment]
The logs has the following
```
2015-09-27 10:58:24,241 ERROR Master$: The provided ip 172.16.0.3 and port 3009 doesn't conform with config at gearpump.cluster.masters: 127.0.0.1:3000
```

**Comment by clockfly** [comment]
@kkasravi 

This is by design.
There can be multiple master nodes. This is essential to discover other master nodes and form a akka cluster.
