### ISSUE TITLE
Propose to attach jar files in submitdag api

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1450]
Currently to submit a dag, we need to submit corresponding jar files individually. If the application is terminated, the system does not have the obligation/knowledge to remove uploaded jars. We need to absorb `uploadjar` api and change`submitdag`, so that upload jar files and submit dag will be executed in one transaction.

**The Design Thoughts**
The current `submitdag` request has an application description (see `SubmitApplicationRequest`). Any processor in the description can be associated with an `AppJar` object, which consists of a form entity name and the file path to the uploaded file. 

Now I propose to change `submitdag` as follows:
1. Move the application description into object `app`. 
2. Any `AppJar` object will only have a form entity name, the file path will be empty. 
3. The request can carry 0-n files. Their form entity name starts with `"file_"`.

So backend will first save all jar files and then fill the file paths with the corresponding file paths. **As a todo, app master should remember these temporary uploaded files and remove them, when the application is terminated.** 

Speaking to the dashboard UI part, when create a processor/edge, user need to have an extra step to choose a jar, before entering a task class or a partitioner class. If dashboard uses `JsZip`, we can reduce several steps. 

How does it sounds like?

**Comment by stanleyxu2005** [comment]
The current use case #491 will restrict only one jar file to be uploaded and all processors will be assigned with this jar file.

**Comment by whjiang** [comment]
+1 for me though I am not an expert on web services.

**Comment by kkasravi** [comment]
I like the submitdag changes. Do we have any ideas if the user wanted to access a 'library' of processors, sort of like importing a partial graph? Probably out of scope for this but we will likely need this functionality too.

**Comment by stanleyxu2005** [comment]
@kkasravi Will the partial graph idea impact the api? If it will not, I will continue the api refactoring work.

**Comment by kkasravi** [comment]
I think it would be similar - so proceed

**Comment by huafengw** [comment]
Migrated to https://issues.apache.org/jira/browse/GEARPUMP-65
