### ISSUE TITLE
If-statement support in DAG

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump#1456]
# Goal

Currently, in Gearpump, publisher will publish each message to all the subscriptions. However, there are cases that need to selectively publish to certain subscription. E.g. in fraud detection use case, a threshold will be checked to determine which route to go (a good user, a bad user or a suspicious user?). Basically, this routing was represented as an IF-statement. 

```
if (is_from_good_user(message)) 
    no more check needed
else if(is_from_bad_user(message))
    alert and no more check needed
else
    perform additional check to decide
```

To support such routing, we need selectively route at processor level. (#1343 is on task level instead of processor level.)

# Solution
## solution 1
Solution 1 is a workaround solution. No change need from Gearpump core part. Each If-then-else statement was represented as 2 processors
```
upstream ~> conditionTrueFilter ~> thenClause   #filter out the false condition messages in conditionTrueFilter
upstream ~> conditionFalseFilter ~> elseClause  #filter out the true condition messages in conditionFalseFilter
```

The main advantage of this solution is no need to change any code at Gearpump core side.

The main disadvantages are:
*  It is hard to maintain. E.g. for dynamic DAG, if such day in future we need to change the condition, we need to carefully change both nodes. Otherwise, they will be inconsistent.
* Bad performance. if the two condition filters are not at the same JVM as upstream. It means we will see significant network transport which is unnecessary. 
*  Hard to understand. User need to learn this BKM to write if-statement.
*  Bad to express on UI. From DAG structure, it is impossible to know which one is the ```then``` clause and which one is the ```else``` clause. So, user is unable to have insight of the goodness of the condition check. E.g. does the condition check succeed in most cases?

## Solution 2
Solution 2 is to add built-in support for if-statement. Basically, the design is:
1. Allow a processor to have more than one output channels. Each channel has a name. Each channel has a default output channel named "out". Processor can add alias names. 
2. Each channel can have multiple subscribers. Thus, for dynamic DAG, user can dynamically add/remove subscriptions for certain channel. 

So, it is quite easy to implement if-statment support using this solution:
* A special ```IFProcessor``` is created. It has two output channels ```then``` and ```else```. UI can show the channel name on edge. Inside ```IFProcessor```, user can write code ```output("then", msg)``` to output to ```then``` channel.
* DSL can be expressed like this
```
  upstream.if(condition, thenClause, elseClause)
```
or
```
   val ifStmt = upstream.if(condition)
   ifStmt.then(thenClause)
   ifStmt.else(elseClause)
```
* Low level API can express as 
```
  A#"then" ~ partioner ~> B
```

**Comment by kkasravi** [comment]
I think the goal is good although sort of makes it seem like you're describing just if else rather than if then else if then else if else. That is I think you're describing selective output based on filter criteria. A few questions:
1. For the solution the IFProcessor can only make 2 choices based on filter conditions. Is this sufficient? 
2. How would the current low level DSL be modified eg A ~ B ~> C?

**Comment by whjiang** [comment]
Hi Kam,

Good questions. 
1. You can regard IFProcessor as an auxiliary utility processor (user can implement his own version). IFProcessor is builtin Gearpump for easy of use. This one is optional.
2. For low level DSL, I think you suggestion is good! I am not sure whether this is workable or not in scala ```A#channel ~> C``` (my preference)

**Comment by whjiang** [comment]
Just realized that @manuzhang has raised a similar issue #1377. I think the solution for this solution can cover #1377 while having dynamic DAG in consideration (as pointed out by @clockfly in #1377 comment).

**Comment by manuzhang** [comment]
Solution 2 is like how storm does it. It would be better if the design doc could incorporate changes to `Task` interface and `Subscription`. These are all tricky parts and impact performance. Channel is a good abstract but what it is at task level ?

**Comment by whjiang** [comment]
@manuzhang I think, at task level, we can the same channels as `processor`. And each Task has following APIs:
```
1. def getChannel(name: String): Channel
2. def send(channel: Channel, msg)
3. def send(msg) = send (defaultChannel, msg)
```
With these APIs, we can avoid lookup for channel at each message.

For transportation layer, I think we can move the code from Task to Channel.

**Comment by kkasravi** [comment]
What does Channel look like. Would it be more transparent for the Task to set an active channel and then just call output?

**Comment by whjiang** [comment]
@kkasravi for most Tasks, they can just use the API
```
def send(msg) 
```
This is exactly the same as before. So, Channel is transparent to them. There is always an active (or default) channel set for each Task (if it has any output link).

Only for `If` and some other special Tasks, they need to be aware of channel.

**Comment by kkasravi** [comment]
Where is `def send(msg)`?
![screen shot 2015-10-15 at 12 19 40 pm](https://cloud.githubusercontent.com/assets/146453/10525028/68fc3fec-7337-11e5-8f5e-a48832a6e596.png)

**Comment by whjiang** [comment]
Hi @kkasravi,

Sorry the code I mentioned is just for explanation instead of actually code. The actual code is at `TaskContext.output(msg)`

**Comment by manuzhang** [comment]
After discussion with @clockfly, we have some concerns over the channel approach.

Think about the use case that a processor A wants to selectively send messages to processors B, C or both of them.

As far as I  can see, there could be two solutions. (ch = channel)

#### solution 1

```scala
A#ch1 ~> B
A#ch2 ~> C

class A extends Task {
   if (condition1) {
      output(ch1, message)
   } else if (condition2) {
      output(ch1, message)
      output(ch2, message)
   } else {
      output(ch2, message)
   }
}
```

The limitations are 

1. what if later A only wants to send message to C on condition2 ?
2. what if we want to add another processor D and A sends messages to D on a new condition ?

#### solution 2 

```scala
A#ch1 ~> B
A#ch2 ~> B
A#ch2 ~> C
A#ch3 ~> C

class A extends Task {
  if (condition1) {
     output(ch1, message)
  } else if (condition2) {
    output(ch2, message)
  } else {
    output(ch3, message)
  }
}
```

Then if A only wants to send message to B on condition1,  B can unsubscribe to channel2. However, it is still suffering if we want to add more downstream processors on new conditions.

#### alternative solution

An alternative solution is to extend the capability of Partitioner to have a `filter` function.  For a DAG like

```scala
A ~ P1 ~> B
A ~ P2 ~> C
``` 

P1 could filter out messages that B are not interested in and P2 can do the same for C. Whenever we want to add more downstream processors, we could add such a partitioner as well. Or if later B wants to receive all messages from A, we can replace P1.

**Comment by whjiang** [comment]
@manuzhang I think what I proposed is your solution 2. 
For the new condition issue you mentioned, I will prefer to using dynamic DAG to handle that by replacing the A node. From my point of view, one output channel shall cover 95% usage, and a simple if-processor to support two channels may cover 4.5% usage. The rest 0.5% usage needs complex routine logic. In it, there may be some cases needs such dynamic support, which can seek the help from dynamic feature. And it shall do so as it is a dynamic change.

I am a little hesitate for Partitioner solution. The reason are:
1. you need to pass same condition (opposite) to two partitioners to filter for simple if-processor. This will be a code duplication problem for maintenance. 
2. what if the condition computing has side-effect. E.g. If the condition is to query the central bank for which a consumer is good or not. And this query is not free. It easily lead to double billing.
3. Harder to present on web UI for DAG. For channel approach, each channel has a name. So, it is quite easy to show the Y/N stream on web UI for if-processor. For partitioner solution, it is harder to do so.

**Comment by kkasravi** [comment]
For high-level DSL's like akka-streams this type of logic is typically found in transformation functions like filter. Functions like filter, drop, merge, take, splitWhen, etc are found in Flow[+T]. Flow is materialized into a akka-stream processor. From the akka-streams documentation for [Flow](http://doc.akka.io/api/akka-stream-experimental/0.2/index.html#akka.stream.scaladsl.Flow):

>It should be noted that the streams modeled by this library are “hot”, meaning that they asynchronously flow through a series of processors without detailed control by the user. In particular it is not predictable how many elements a given transformation step might buffer before handing elements downstream, which means that transformation functions may be invoked more often than for corresponding transformations on strict collections like List. *An important consequence* is that elements that were produced into a stream may be discarded by later processors, e.g. when using the #take combinator.

This would suggest - especially when flattening the akka-streams Graph to our Graph, we keep this logic within Processors not Partitioners.

**Comment by manuzhang** [comment]
Shall we move this forward ?

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-68
