### ISSUE TITLE
Provide YARN related option that can disable creating the services UI when the YARN application master creates the Master and Workers

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1460]
For integration with TAP we need to be able to NOT spawn the services UI, since this will be created within TAP as a user facing process by the GearPump broker at the same time the broker creates YARN GearPump applicationmaster

**Comment by huafengw** [comment]
Hi Kam, the related test failed. I set ```gearpump.service.enabled``` to false in test and it failed. But it will pass if the config value is true.

**Comment by kkasravi** [comment]
Hi @huafengw 

Here is how I tested this.

1. I changed conf/yarn.conf setting to false
![screen shot 2015-10-08 at 9 45 02 am](https://cloud.githubusercontent.com/assets/146453/10360488/52f6a26e-6da1-11e5-980a-51ade18edc28.png)
2. I started gearpump on yarn
3. I went to where the yarn application master writes it's logs
![screen shot 2015-10-08 at 9 47 11 am](https://cloud.githubusercontent.com/assets/146453/10360520/996da71a-6da1-11e5-945c-a434c1702838.png)
4. I verified that there is no message that the UI REST service is running (stdout is 0 length)
5. I tried browsing to where the UI REST service is normally and confirmed no page
![screen shot 2015-10-08 at 9 49 28 am](https://cloud.githubusercontent.com/assets/146453/10360568/e656ecf8-6da1-11e5-82a6-76f500f844e4.png)
6. I then re-enabled the setting
![screen shot 2015-10-08 at 9 51 01 am](https://cloud.githubusercontent.com/assets/146453/10360604/1f75be2e-6da2-11e5-93c0-9e5ebfb9d406.png)
7. I re-started gearpump on yarn
8. I went to where the yarn application master writes it's logs and verified that the UI REST service started
![screen shot 2015-10-08 at 9 52 28 am](https://cloud.githubusercontent.com/assets/146453/10360637/5ed9bda4-6da2-11e5-9062-031060aadd12.png)
9. 5. I browsed to where the UI REST service is normally and confirmed it was up
![screen shot 2015-10-08 at 9 54 19 am](https://cloud.githubusercontent.com/assets/146453/10360665/95873714-6da2-11e5-952b-ba165f8b8069.png)

Which test did you run that failed?

Thanks
Kam

**Comment by huafengw** [comment]
I just run the YarnApplicationMasterSpec and it failed.

**Comment by kkasravi** [comment]
Hi @huafengw - should be fixed now. I ran YarnApplicationMasterSpec and there were no errors
