### ISSUE TITLE
Clean up release notes

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1475]
I noticed there is a directory `notes` for change logs. We also have a CHANGELOG.md at root. We dont need to maintain two release notes. @manuzhang could you find a way to publish release notes from CHANGELOG.md.

**Comment by manuzhang** [comment]
The `notes` directory is used to publish releases notes to [implicity.ly](http://notes.implicit.ly/) which has a large audience among the scala community and beyond. Also, a lot of popular scala projects have been publishing release notes to implicitly. I've been maintaining these notes and publishing them and I don't find it a burden as we don't release so frequently.

**Comment by stanleyxu2005** [comment]
Ask implicitly for suggestion. Or move the notes to the doc site.

**Comment by whjiang** [comment]
So, shall we remove CHANGELOG.md instead?

**Comment by manuzhang** [comment]
I think keeping change logs in `CHANGELOG.md` is a good convention. What's in `notes` could be more than change logs with highlights and a brief introduction for new features. As I said, I've been very happy to write those notes and publish them, which doesn't cost a lot of time. Why not keep both ? I don't see we are troubled or burdened by them.

**Comment by whjiang** [comment]
+1 for keep them both.

**Comment by stanleyxu2005** [comment]
CHANGELOG.md should be there. 

Notes are good, but they are individual files. I'm suggesting tell implicitly's owner provide an alternative way to manage them. When we have more versions released, the folder will look unite messy. All famous Scalia projects publish their release notes to implicitly in this way?

**Comment by manuzhang** [comment]
Yes. To name but a few,

* [sbt](https://github.com/sbt/sbt/tree/1.0.x/notes)
* [sbt-assembly](https://github.com/sbt/sbt-assembly/tree/master/notes)
* [specs2](https://github.com/etorreborre/specs2/tree/master/notes)
* [shapeless](https://github.com/milessabin/shapeless/tree/master/notes)
* [scalikejdbc](https://github.com/scalikejdbc/scalikejdbc/tree/master/notes)

**Comment by whjiang** [comment]
As long as this is NOT a burden, let's keep both.
