### ISSUE TITLE
Support copy actor path and log location to clipboard for dashboard

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1478]
As we don't have an online log viewer yet. The locations are shown as tooltip. For debugging propose, we'd like to have a convenience way to copy location to clipboard. I checked some js clipboard solutions, clipboard.js is quite lightweight.

**Comment by kkasravi** [comment]
+1 on this feature. We really need a way to get to these logs easily - especially within hadoop/yarn settings.

**Comment by whjiang** [comment]
+1 on this feature.

**Comment by stanleyxu2005** [comment]
![preview](https://cloud.githubusercontent.com/assets/5162687/10669702/89e549b4-7914-11e5-9ab9-edd6cadfaf1c.png)
When mouse is over a location button, the tooltip will now mention "click to copy". If user click the button, the location will be copied to clipboard automatically.

**Comment by whjiang** [comment]
Looks good.
