### ISSUE TITLE
NoSuchElementException when flushing pending messages

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1485]
This is only caused by another Exception from another Task. For example,

If TaskA throws an Exception, Executors will clean up their `remoteAddressMap`s and send `PoisonPill` to all its tasks. It's possible that, before receiving the `PoisonPill`, TaskB just receives `TaskLocationReady` and invokes `SendLater.sendPendingMessages`. Since the `remoteAddressMap` is already cleaned, the a `NoSuchElementException` would be thrown by TaskB.

**Comment by manuzhang** [comment]
@clockfly @huafengw 

Should we add a check for remoteAddress here and log errors ?

```scala
  private def sendPendingMessages(transportId: Long) = {
    val localActor = express.lookupLocalActor(transportId)
    if (localActor.isDefined) {
      flushPendingMessages(localActor.get, transportId)
    } else {
      val remoteAddress = express.lookupRemoteAddress(transportId)
      flushPendingMessages(remoteAddress.get, transportId)
    }
  }
```

Either way, the task will be restarted because of the exception from another task (see above) and pending messages will be lost.

**Comment by clockfly** [comment]
So we are still able to recover from this exception?

If so, I think we should change the change this exception type to something more meanful name.

**Comment by manuzhang** [comment]
Yes if the exception causes this exception is recoverable. Do you mean we check and throw explicitly with a meaningful exception name if `remoteAddress` is null ?
