### ISSUE TITLE
Support IoT temp isolation model

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump#1507]
One important characteristics of IoT deployment is that: the edge device can be temp out of reach from data center. This out-reach can last days, even weeks. 

And the typical deployment requires that, when such a dis-connection happens, the edge device shall be able to run the deployed task continuously and flush its output to local disk. And when the connection reestablished, the stored events will be resend to data center.

I am not sure how difficult for Gearpump to support such a model. But, if we want to target IoT, this is a MUST HAVE, I assume.

**Comment by whjiang** [comment]
according to Gearpump Actor Hierarchy,

![](http://www.gearpump.io/site/img/actor_hierarchy.png)

Worker and Executors have been closely monitored/supervised by Worker Manager and AppMaster. Thus, any network isolation of a worker will be regarded as a worker failure. This makes the IoT case with network isolation impossible. 

I think we have several solutions here:
1. relax this monitor/supervision chain. That is, for certain worker/executor, admin or user can specify that this is remote on edge device. So when network isolation detected, Worker manager and AppMaster can handle it with different strategy. However below are the uncertainties (need further investigation):
  - what will worker/executor behave when it find himself isolated? Is there any policy to configure? Or it will die immediately?
  - how to route executor output to a temp storage transparently? I assume transparency is a desired feature.
2. keep edge device as a whole actor hierarchy. That is, edge device runs its own gearpump service instance. So basically, the data center gearpump cluster (DC) and edge device gearpump cluster/service (EDGE) are separate. But, add some facility to allow DC to control EDGE (upload app, kill app, etc). This is easier. The main drawback here is we lose the task move transparency. In no. 1 solution, we actually can move task between edge and data center transparently as they are the same gearpump. But, in this solution this is no longer possible.

**Comment by stanleyxu2005** [comment]
Solution 2 sounds reasonable. Data transparency is IMO required for computing intensive devices. For IoT devices e.g. temperature sensors, CCTVs, they are location based. Why they need a task move transparency?

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-67
