### ISSUE TITLE
message semantics guarantee in Gearpump

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1528]
As writing documentations for storm and reliable message delivery, I find it hard to explain the message semantics guarantee provided by Gearpump in a clear way.

Here is the problem,
We track message loss and replay from the minimum timestamp of all the pending messages in the system. This provides at least once semantics only with a `TimeReplayableSource`. For other sources, the replayed messages are not failed messages but new messages with old timestamps and hence only at most once is guaranteed. In that case,  it doesn't make a difference if we send messages in a fire-and-forgot manner and don't track message loss at all.

**Comment by whjiang** [comment]
Hi Tianlun,

I think the goal for us is to support at least once. We need to make `DataSource` support replayable. If the datasource itself is NOT replayable, we need to add a wrap layer to make it replayable (just like what Spark Streaming did). This wrapper is missing now.

**Comment by manuzhang** [comment]
why is there no at most once mode ? Is at least once required for all sorts of applications ?

**Comment by huafengw** [comment]
I think we should add an option to switch to at most once mode.

**Comment by manuzhang** [comment]
superseded by #354
