### ISSUE TITLE
gearpump website get-start need update

### ISSUE THREAD

**Issue by darionyaphet** [gearpump/gearpump#1542]
I'm begin learning gearpump today and reading User Guide. 
I found `Run a distributed application in 30 seconds.` -  `Step2: Submit application` word-count.jar file name had changed . This Document need to be update  :P .

**Comment by manuzhang** [comment]
@darionyaphet, thanks for your interest. We are refactoring our doc sites, which will be released soon. Please open related issues to https://github.com/gearpump/gearpump.github.io

**Comment by darionyaphet** [comment]
Good Job :+1:  Thank you for you hard work~~
