### ISSUE TITLE
gearpump.io visually degradated - cannot load .css

### ISSUE THREAD

**Issue by karol-brejna-i** [gearpump/gearpump#1551]
on overview.html
GET http://www.gearpump.io/css/bootstrap-responsive.min.css 
GET http://www.gearpump.io/css/bootstrap.min.css 
give 404

**Comment by kkasravi** [comment]
thanks @karol-brejna-i - merge to master was premature for 0.6.2 - we're working on it.

**Comment by kkasravi** [comment]
Fixed
