### ISSUE TITLE
all services dependencies need to be in fat jar

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1578]
This is required for CF deployment - where services can be launched with just one jar

**Comment by karol-brejna-i** [comment]
Please, mind that Java build pack (https://github.com/cloudfoundry/java-buildpack - a mechanism for deploying JVM apps on Cloud Foundry) has two limitations:

* the app should listen only on one port
* the app should bind to the port set in PORT environment variable (set by Cloud Foundry) 

Now, the app looks http port up in gear.conf. 
```
  services {                                                                                                         
    host = "0.0.0.0"                                                                                                
    http = 8090                                                                                                      
    ws = 8091                                                                                                        
  }
```
Is there a command line switch (when starting 'services') to make sure ws port is disabled?

**Comment by stanleyxu2005** [comment]
@karol-brejna-i Websocket can be disabled in gear.conf. SFAIK, websocket is used to report metrics and for the time being we only fetch metrics from 8090 port. So its safe to turn it off.

**Comment by clockfly** [comment]
Looks like karol has found a way to pack the project. close this now.
