### ISSUE TITLE
gearpump yarnclient needs to be able to read/write from kerberos enabled HDFS

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1604]

**Comment by huafengw** [comment]
Hi Kam, what kind of data do you want to write to HDFS? Since Gearpump can already be launched in kerberos-enabled Yarn, which means the client side's configuration file is successfully uploaded to secured HDFS.

**Comment by huafengw** [comment]
@kkasravi Hi Kam, any update on this issue?

**Comment by kkasravi** [comment]
yes this works so closing.
