### ISSUE TITLE
StormBoltOutputCollector should not report on ack disabled

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1630]

**Comment by clockfly** [comment]
Is this consistent with storm?

When ack is disabled, the ack call will be skipped? or will be also called?

**Comment by manuzhang** [comment]
yes.  `bolt.ack` is actually called by applications. When ack is disabled, ack could be called but since the tuple tree is empty, there will be no ack messages. We don't skip ack but reporting ack, which is consistent with Storm.

**Comment by manuzhang** [comment]
this is already fixed #1631. Please file new issues if there are any concerns.
