### ISSUE TITLE
In integration test, streaming app should always check its' clock status

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1635]
The integration test did not check whether a running streaming type application reports its clock. We accidentally changed the timeout setting, which cause clock not running. And this issue was not encountered. The issue is described in https://github.com/gearpump/gearpump/issues/1636

We need to fix related test case to ensure this will not happen again.

**Comment by stanleyxu2005** [comment]
It is really wired, I did the same test. 
* On dashboard, I submit a wordcount and 10 seconds after the application is started, it becomes dead. Uptime will not go. 
* I submit a wordcount in integration test environment (Docker cluster) using the same REST api, the application lives for 10 minutes without any problem. In the meanwhile, I periodically check metrics, stallking tasks, etc.

**Comment by manuzhang** [comment]
@stanleyxu2005 Do you reproduce this every time ? Any error log ?

**Comment by stanleyxu2005** [comment]
@manuzhang The logs look like some out of memory issue. I have increase number of process from 1024 to 4096 `ulimit -u 4096`, until now the issue does not appear.
[*.txt](https://github.com/gearpump/gearpump/files/50759/default.txt)

**Comment by stanleyxu2005** [comment]
Cannot reproduce
