### ISSUE TITLE
YARN deployment - no easy way of obtaining master address when deployed without services

### ISSUE THREAD

**Issue by karol-brejna-i** [gearpump/gearpump#1640]
GearPump master on YARN is normally available in GearPump UI (`services`).

After deploying GearPump on YARN with  `SERVICES_ENABLED` set to false there is no easy way to get master address -- the address required by `services`.

**Comment by kkasravi** [comment]
## Requirements

> 1. Ability to return the master(s) from the yarnclient so the services UI can be launched in a different environment
2. Make it compatible with YARN with perhaps a YARN JIRA for improved functionality if the solution is less than desirable

## Problem Description
Currently the YARN client provides a way to retrieve a tracking URL from the YARN ApplicationMaster once the ApplicationMaster has been submitted. This tracking URL is part of the ApplicationReport returned by the ApplicationMaster and is intended to provide a web interface to the application. Unfortunately this web interface needs to be launched within a cloud foundry environment using information where the master(s) are located. We would like the YARN client to output to the console information about the master(s) which can then be used to launch the services within the Cloud Foundry environment. There doesn't appear to be any information within the ApplicationReport that would provide this type of information. Nor does there appear to be a way to extend the ApplicationReport easily to provide an application specific API. In fact YARN does not provide much formal REST support for the tracking URL (https://issues.apache.org/jira/browse/YARN-2084) nor an ability to get much meta-data within the ApplicationReport that could support this type of think. There was a hack to provide unmanaged AM capability which isn't what is needed here.
