### ISSUE TITLE
add exactly-once spec to integration-test

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1641]
@stanleyxu2005 please help to add a HDFS docker image like that for Kafka

**Comment by stanleyxu2005** [comment]
Do you mean, you want a Kafka cluster Docker image with HDFS installed?

**Comment by manuzhang** [comment]
No, just an HDFS image.

**Comment by stanleyxu2005** [comment]
Try this one `sequenceiq/hadoop-docker`, which is planned for Gearpump over YARN.
