### ISSUE TITLE
failed to change processor's parallelism from dashboard

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1651]
Response is ```The request's content is not supported. Expected: multipart/form-data```

**Comment by stanleyxu2005** [comment]
Acha, the change of file server actually breaks the existing code. When I wrote integration test, I thought `curl` was not encoding request in correct form type, so I added a dummy file in integration test (https://github.com/gearpump/gearpump/blob/master/integrationtest/src/main/scala/io/gearpump/integrationtest/minicluster/RestClient.scala#L167) So integration test works...
