### ISSUE TITLE
failed to replace processor successfully

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1653]
It's caused by the former refactor of Task and Executor

**Comment by stanleyxu2005** [comment]
Interesting. We have already test case for changing a processor (description, paralism, etc.). Better add a test case along with the fix

**Comment by manuzhang** [comment]
But we don't check for clock advance

**Comment by stanleyxu2005** [comment]
Will create a test case individually https://github.com/gearpump/gearpump/issues/1655
