### ISSUE TITLE
YARN ApplicationMaster should launch the services actor in a separate process.

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1658]
This is required for integration with the TAP Gearpump broker.

**Comment by clockfly** [comment]
No longer valid

**Comment by darionyaphet** [comment]
Someone could tell me what is `TAP Gearpump broker` ?  thanks :)

**Comment by clockfly** [comment]
@darionyaphet 

TAP is a open source machine learning and service management infrastructure. Gearpump is integrated into TAP.
See one page introduction at: http://trustedanalytics.org/wp-content/uploads/2015/09/TAP-_Overview_web.pdf
website http://trustedanalytics.org/

**Comment by karol-brejna-i** [comment]
@darionyaphet 

Trusted Analytics Platform has the notion of services Marketplace. 

The marketplace presents to the user and allows him to provision resources on demand. These resources are known as service instances. Examples of resources (managed services) include datastores (Redis, ElasticSearch, MongoDB, Neo4j, PostgreSQL, etc.), messaging system (Kafka, etc.) and many others.

We want the user to be able to spawn his own GearPump cluster in a matter of single mouse click (in the marketplace).
GearPump Broker is responsible for the instantiation.

Hope this helps.
