### ISSUE TITLE
ContainerLaunchContext#getAMLocalResourcesMap will convert Failure to an empty Map

### ISSUE THREAD

**Issue by Renkai** [gearpump/gearpump#1660]
I think it will eat some error info and make users harder to know what's going wrong.

**Comment by stanleyxu2005** [comment]
The change will change default behavior. Need to update all calling points to handling exception...

**Comment by Renkai** [comment]
@stanleyxu2005 This method only used when submit a cluster to YARN.I think it's ok to just throw error here,print error on console,and stop the process.It could be a fatal error if file system was not well configured.

**Comment by manuzhang** [comment]
@huafengw could you look at this ?
