### ISSUE TITLE
Source task that emits messages per a schedule (interval or otherwise) should be provided

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1665]
Currently we do not have a easy way to emit data events at specific intervals from a source task other than using scheduleOnce with time related values that have been added to a specific type of source (for example [stockcrawler](https://github.com/gearpump/gearpump/blob/22f1a76cd842e9eb669f0e41d46c3440a3fcb334/examples/streaming/stockcrawler/src/main/scala/io/gearpump/streaming/examples/stock/Crawler.scala). We should provide a generic type of source task which can emit new message using a config object that is provided by the user.

**Comment by manuzhang** [comment]
Do we need a wrapper at Task level or just add something like `Timer` to DSL ?

**Comment by kkasravi** [comment]
@manuzhang  Would the Timer result in a special type of Source task? How would the DSL look? It might make sense to see how it could be added to the DSL similar to something like filter and see how that plays out in the DSL Operation types.

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-100
