### ISSUE TITLE
Timeout to retrieve worker list after killing a worker shortly

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1671]
Steps to reprodure: 
1. Create 5 workers
2. Query workers `http://127.0.0.1:8090/api/v1.0/master/workerlist`. It will return 5 workers.
3. Kill 1 worker in console
4. Query workers again. It might timeout.
5. After seeing the timeout, query workers again, it will return 4 workers.

*Update 1*: My suggestion is to use a central repository to store cluster state.

**Comment by clockfly** [comment]
@stanleyxu2005

It will take master some time to find a worker is killed, typically it can take up to 10 seconds. 
As the same time, the UI is responsitive to other queries, like http://127.0.0.1:8090/api/v1.0/master

So, what is your expected behavior?

**Comment by stanleyxu2005** [comment]
I imagine we have a central repository to store state. So when dashboard/client queries worker status, it should contact the repository instead of asking the worker itself. So that we will not meed a AskTimeoutException like this. Before a worker is killed effectively, the state of the worker in repository is still active. Another benefit is that we have a list of killed workers, not like the current solution that all killed workers are no longer in record.

**Comment by clockfly** [comment]
@stanleyxu2005 

The worker status we want to query is only available by querying worker node.
```
[{"workerId":0,"state":"active","actorPath":"akka.tcp://64dfe6dd-e65f-4547-9563-d48c175efea7@127.0.0.1:57929/user/Worker64dfe6dd-e65f-4547-9563-d48c175efea7","aliveFor":"315607","logFile":"C:\\myData\\gearpump\\output\\target\\pack\\logs","executors":[],"totalSlots":1000,"availableSlots":1000,"homeDirectory":"C:\\myData\\gearpump\\output\\target\\pack","jvmName":"16232@XZHONG10-MOBL"}]
```

But now, it looks like the timeout settting is set to 90 seconds, that is unbearable long wait. 
It is introduced by:
https://github.com/gearpump/gearpump/commit/fd4528daae0f049bba127bd9c9187669563a0fef#diff-817b8424c145ed50ac3dada25b6b03ac

I think we should revert it back to 15 seconds. Then the UI don't looks like dead, how do you think?

**Comment by stanleyxu2005** [comment]
No, I was querying `/workerlist`
