### ISSUE TITLE
HBaseSink regression from 0.7

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1713]
We used to be able to add a Configuration parameter to HBaseSink which would a HBaseProperties.ZOOKEEPER_QUORUM to be passed to the constructor. Now this is no longer possible and breaks an example. See below 

```
public abstract class BaseRepository {

    protected final String tableName;
    protected final Configuration hbaseConf;

    public BaseRepository(UserConfig userConfig) {
        String tablePrefix = userConfig.getString(HbaseProperties.TABLE_PREFIX).get();
        tableName = tablePrefix + HbaseValues.TABLE_NAME;

        String zkQuorum = userConfig.getString(HbaseProperties.ZOOKEEPER_QUORUM).get();

        hbaseConf = new Configuration();
        hbaseConf.set(HbaseProperties.ZOOKEEPER_QUORUM, zkQuorum);
    }


    public void createTable() throws IOException {
        HBaseSink sink = getHbaseSink();
        try (Connection conn = sink.connection(); Admin admin = conn.getAdmin()) {
            if (!admin.tableExists(getTableName())) {
                HTableDescriptor table = new HTableDescriptor(getTableName());
                for (String family: HbaseValues.COLUMNS_FAMILIES) {
                    table.addFamily(new HColumnDescriptor(family));
                }
                admin.createTable(table);
            }
        }
    }

    public abstract TableName getTableName();

    protected HBaseSink getHbaseSink() {
        return new HBaseSink(UserConfig.empty(), tableName, hbaseConf);
    }
}
```

**Comment by huafengw** [comment]
Hi Kam, I remove the Configuration when constructing a HBaseSink because when submitting an application, the classpath of command ```gear``` does not contains HBase's conf folder. So constructing a Configuration at client side may be inconsistent with cluster side.
What is that HBaseProperties.ZOOKEEPER_QUORUM used for?

**Comment by clockfly** [comment]
@huafengw 

You can not be sure where is the HBase cluster, or whether multiple hbase cluster are installed on same machine. 

So think, the HBase conf as the constructor parameter is still necessary. 

By the way, the doc on gearpump.io don't reflect current code.
