### ISSUE TITLE
All UI buttons become inactive after going into Details once

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1715]

**Comment by manuzhang** [comment]
@kkasravi does this happen every time ? Do you have a snapshot ?

**Comment by stanleyxu2005** [comment]
how to reproduce

**Comment by kkasravi** [comment]
Does not happen on 0.7.0. Happened on 0.7.1-SNAPSHOT. I'll reverify this behavior after demo is over. (Demo in apprx 14 hours)

**Comment by stanleyxu2005** [comment]
I'm quite sure it not happens in master branch. If you find a way to reproduce, then reopen the issue.
