### ISSUE TITLE
Resource isolation per application with linux container

### ISSUE THREAD

**Issue by Renkai** [gearpump/gearpump#1723]
If CPU/memory resource could be limited by application,like Spark on YARN,it would be really great.Do you have some plan to do this?

Thanks.

**Comment by clockfly** [comment]
Do you mean fine-grain resource scheduling? or cgroup/linux container?

**Comment by Renkai** [comment]
Yes

**Comment by clockfly** [comment]
Which one?
A: resource scheduling? -
B:  cgroup/linux container?

A or B?

**Comment by Renkai** [comment]
I think A and B do the same thing,could you explain some difference about them?

**Comment by clockfly** [comment]
It is different.

Fine-grain resource scheduling means scheduling resource like mapreduce job. More resource will be allocated dynamically when there are more task. 
cgroup/linux container means setting limit like CPU, memory, network for a single yarn container, or mapreduce task.

I know spark have fine-grain resource scheduling, but I don't know whether spark support linux container or not.

**Comment by clockfly** [comment]
What is the problem you want to solve? 
Do you want better resource isolation between different streaming application? Or other suff.

**Comment by Renkai** [comment]
I want cgroup/linux container, because I want many different developers can share the same cluster and no one will consume too many resources or damage other ones application by accident.

**Comment by clockfly** [comment]
Summary of User Story:
In same Gearpump Cluster, there can be multiple user application running. We want to limit the resource used by each user application, so that one user app will not interference other user app.

Scope:
This is not about resouce scheduing with YARN or Mesos. But about how to assign and control the resource assigned for each app.

**Comment by clockfly** [comment]
@huafengw 

Do you want to post your idea here?

**Comment by huafengw** [comment]
Should we follow JStorm's pattern? Generally we can let user set Executor's maximum CPU usage for every application.

**Comment by clockfly** [comment]
@huafengw  I think it is a good idea. Can you post the design here so that others can understand?

**Comment by huafengw** [comment]
Fox example, when submitting an application to Gearpump with CGroup enabled, user can specify a configuration called ```gearpump.executor.cpu.core.upper.limit```, which is a Int value represents the maximum cpu cores per Executor process can use. 
That's just what JStorm exposes to their end user.

**Comment by clockfly** [comment]
@huafengw  added an experiment module https://github.com/gearpump/gearpump/tree/master/experiments/cgroup

The work is based on Storm(JStorm), it can only set the CPU limits now.

The document is here: https://github.com/gearpump/gearpump/blob/master/docs/deployment-resource-isolation.md

**Comment by clockfly** [comment]
Next step is to combine cgroup resource isolation with scheduling, so that we don't allocate new executor process on a full loaded machines.

**Comment by clockfly** [comment]
@Renkai 

Do you want to try this out? So that we can get some feedback.

**Comment by huafengw** [comment]
Initial support for CGroup is implemented. Please raise new issues in [Gearpump Jira ](https://issues.apache.org/jira/browse/GEARPUMP) when there are new requirements.
