### ISSUE TITLE
Add Gearpump to Yahoo's streaming-benchmarks

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1732]
See https://github.com/yahoo/streaming-benchmarks

**Comment by darionyaphet** [comment]
Yahoo! released a blog [Benchmarking Streaming Computation Engines at Yahoo!](http://yahooeng.tumblr.com/post/135321837876/benchmarking-streaming-computation-engines-at)

**Comment by clockfly** [comment]
@huafengw  Can you post your test result here?

**Comment by huafengw** [comment]
Here is the pull request https://github.com/yahoo/streaming-benchmarks/pull/10
