### ISSUE TITLE
Provide an accessible site where demo's can be shown

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1735]
Those with admin rights can submit applications

**Comment by clockfly** [comment]
1. For normal account, only have the permission to see the demo, no permission to submit a new app
2. For special user in whitelist, have the permission to submit an application.
3. The user is logined, it will be forced to log out after a timeout(safer in this way to host on public cloud)

**Comment by clockfly** [comment]
Here is a aws site for temporary usage. http://52.53.210.64:8090/

It is good to demo Gearpump though the machine only have 1 core and 1GB memory.
