### ISSUE TITLE
Propose to define processor types

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1751]
Currently we all call them processors, but as you know, processors can be sightly different. Here are the types I see:

1. Only has outputs, no inputs (data source)
2. Only has inputs, no outputs (data sink)
3. Has both inputs and outputs

If this terminology makes sense, it will help user to understand the infrastructure of an application more clearly. And dashboard can use processor types to do:

1. Render DAG nodes in different colors
2. Filter particular processor types for inspection

What is your thoughts on this?

**Comment by kkasravi** [comment]
+1
See #1383 which was never merged. I think this will be a requirement to handle upcoming integration challenges with TAP, ATK. Also, perhaps now within the context of akka-streams this now makes more sense.

**Comment by kkasravi** [comment]
[PR](https://github.com/apache/incubator-apex-malhar/pull/133/files) to add nifi operators to apex's malhar library. This is their way to add new operators to the malhar [repo](https://github.com/apache/incubator-apex-malhar). Similar concept: how to easily add different types of processors and make them available.

**Comment by whjiang** [comment]
+1 on the general idea.

@stanleyxu2005, what the expected behavior to tell processor type? subclass?

**Comment by stanleyxu2005** [comment]
Currently dashboard check the number of inputs and outputs. Subclasses is a good idea.

**Comment by kkasravi** [comment]
Pickle has a particular way of conveying subclasses. I think different JSON serialization libraries do it in different ways. Having icons specific to source, sink based on inputs, outputs seems conservative and safe. When I did the scalajs classes related to metric types I encoded the class type in the serialization so the javascript side could build the correct Map[type, list] subcategories.

**Comment by kkasravi** [comment]
Moved to JIRA. See https://issues.apache.org/jira/browse/GEARPUMP-84
