### ISSUE TITLE
support Storm 0.10

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1767]
Storm has released 0.10 with bug fixes and new features including

1. added authentication and authorization
2. added external connectors, redis, jdbc, hive and flux 

I already have a [working branch](https://github.com/manuzhang/gearpump/tree/storm_0.10) to support the basic usage of Storm 0.10 over Gearpump (not including the above 2 features).

The question is how we plan to support Storm 0.9 and 0.10, and future versions.

It's possible to provide two external Storm modules and one facade in one Gearpump version. Users would need to specify which version of Storm application they want to run on submit

**Comment by darionyaphet** [comment]
I'm using Storm 0.9.4 and Storm 0.10 is compatibility with 0.9.X ?

**Comment by manuzhang** [comment]
Not exactly. Storm-kafka has introduced some [breaking changes](https://github.com/apache/storm/pull/493/files)

**Comment by darionyaphet** [comment]
Seems Storm Kafka Spout 0.9.X and 0.10.X using difference argument to control start point .  -.-

**Comment by clockfly** [comment]
@manuzhang 

Sorry, I don't get your point. Does our code have dependencies on storm-kafka module? If not, why there is compatibility concern?

**Comment by manuzhang** [comment]
we have an integration test case `StormKafkaTopology` that depends on storm-kafka module.

**Comment by clockfly** [comment]
For integration test, I think you can define two different test, with one using storm-kafka 0.9, the other using storm-kakfa0.10, right?

Besides the integration test, do you think there are other blockers for us to support storm-0.1 user jobs?

**Comment by manuzhang** [comment]
You are right. We can maintain compatibility for both versions.

**Comment by manuzhang** [comment]
storm 0.10 feature list 

- [ ] basic functionality (storm topology, drpc, multi-lang)
- [ ] integration test
- [ ] 0.9 compatibility
- [ ] storm-kafka (spout / bolt)
- [ ] storm-hdfs (bolt)
- [ ] storm-hive (bolt)
- [ ] storm-hbase (bolt)
- [ ] storm-redis (bolt)
- [ ] storm-jdbc (bolt)
- [ ] flux
- [ ] security
- [ ] (stretch goal) [StreamCQL](https://github.com/HuaweiBigData/StreamCQL)

Note: unable to verify storm-eventhubs which requires access to Microsoft Azure
