### ISSUE TITLE
overall Average Message Receive Latency should not be averaged over Source Processors

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1779]
since Average Message Receive Latency of a Source Processor is always 0

**Comment by stanleyxu2005** [comment]
You want to average:
a. all sink processors or
b. all processors except source processors or
c. all processors that receive throughput > 0

**Comment by manuzhang** [comment]
No latency of 0 should be averaged over since 0 latency doesn't exist. Also note that source processors have receive throughput > 0 and latency of a sink processor is measured between its direct upstream and itself.

**Comment by stanleyxu2005** [comment]
Is this assumed to be a bug for metrics calculation? @clockfly Shall we fix this in 0.7.1?

**Comment by stanleyxu2005** [comment]
On application overview page and DAG page, it will show effective message receive latency. The latency is the duration that a message flows from source to sink. If there are more than one path for message flow, the latency would be the largest latency of the possibilities. 

On processor page, it will still show average message receive latency, which is the average of all processor tasks' message receive latency. 

I hope this PR makes the message receive latency meaningful.
