### ISSUE TITLE
latency of Storm over Gearpump on YARN application is extremely high 

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1781]
![screenshot from 2015-12-25 13 00 02](https://cloud.githubusercontent.com/assets/1191767/12000005/630866bc-ab07-11e5-8354-db9c0033f8e0.png)

**Comment by clockfly** [comment]
Have you looked into this? storm module problem?

**Comment by manuzhang** [comment]
It doesn't happen on stand-alone Gearpump so I don't think it's related to storm module.

**Comment by clockfly** [comment]
But looks like you only use one executor, it doesn't have much difference with standalone mode.

**Comment by clockfly** [comment]
Can you reproduce this everytime?

**Comment by manuzhang** [comment]
yes, every time

**Comment by clockfly** [comment]
Can you grab the metrics rest reply? Do you have a environement we can access?

**Comment by huafengw** [comment]
What about SOL in Yarn mode?

**Comment by manuzhang** [comment]
The rest reply is consistent with that on the dashboard. Sorry, my environment is fragile (check #1384). Other applications are working fine although I've not tried all of them.

**Comment by manuzhang** [comment]
thanks to the findings of @clockfly, the root cause is that the 10 spout tasks sleep for 0.1s every one message and block the maximum 8 threads from thread pool. #1795 will allow users to configure a dedicated thread for a blocking-io task and we need to add documentation for this.

**Comment by manuzhang** [comment]
this is fixed in #1795
