### ISSUE TITLE
"yarnclient" cannot kill a hanging application

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1784]
![screenshot from 2015-12-25 13 39 16](https://cloud.githubusercontent.com/assets/1191767/12000217/d678239e-ab0c-11e5-8002-9ff68de8c824.png)

In the screenshot, `application_1451018909165_0003` is accepted but not running due to lack of container memory so I want to kill it with "yarnclient" from Gearpump . That failed with the following errors

```
Failed to connect YarnAppMaster(tried 1)... host parameter is null
Failed to connect YarnAppMaster(tried 2)... host parameter is null
Failed to connect YarnAppMaster(tried 3)... host parameter is null
...
```

Finally, I managed to kill the application with "yarn" command from Hadoop.

**Comment by clockfly** [comment]
Updated the document
https://github.com/gearpump/gearpump/pull/1786
