### ISSUE TITLE
abnormal gc behavior of Executor

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1816]
Recently I was tuning Gearpump's performance and I found a randomly abnormal gc behavior of Excutor's jvm.
Here is the snapshot of a normal Executor Jvm's gc behaviour:
![normal](https://cloud.githubusercontent.com/assets/5011399/12046328/2b06c6fc-aef2-11e5-9f0e-f6a6cc2254b8.png)
The most of gc activity is minor gc and the used heap is growing very slowly.
While here is the abnormal one:
![unnormal](https://cloud.githubusercontent.com/assets/5011399/12046346/6a86d844-aef2-11e5-9163-b87c047de4fc.png)
You can see the full gc acticity is very often and it eventually will hurt the performance of Task on that Executor.
After continue digging, I found the abnormal jvm will generate a lot of ```akka.dispatch.AbstractNodeQueue$Node``` object:
![node](https://cloud.githubusercontent.com/assets/5011399/12046379/fe4e6eb6-aef2-11e5-9b61-69ad2842ac0b.png)
Here it takes about 243MB of memory while the normal Executor jvm does not take that much.

Then I found there is already a similar issue raised in Akka:  https://github.com/akka/akka/issues/17547

**Comment by clockfly** [comment]
@huafengw 

Yes, this is a good finding. It also puzzles me for a long time. But I am not sure it is the same problem of akka#17547

**Comment by huafengw** [comment]
There is a fix about that issue. I tried to using that fix and build a new related jar to run the application. 
I ran multiple times and seems the weird gc behavior is gone.

**Comment by clockfly** [comment]
Great! Can post the jar somewhere? I can try it locally.

**Comment by clockfly** [comment]
It is worth to do some performance test. I think the improvement will be huge.

**Comment by clockfly** [comment]
Please make a PR to work-around this.

**Comment by huafengw** [comment]
Any advice on how to achieve that?

**Comment by clockfly** [comment]
You can package the unmanaged jar directly.

**Comment by clockfly** [comment]
@huafengw 

Would you mind also paste the performance result here?

**Comment by huafengw** [comment]
Here is the performance benchmark result on a 4-node cluster:
```
+--------------------+------------------------+-------------+
|                    | Throughput(messages/s) | Latency(ms) |
+--------------------+------------------------+-------------+
| Before #1816 fixed | 14,600,000             |           8 |
| After #1816 fixed  | 18,000,000             |           4 |
+--------------------+------------------------+-------------+
```

1.	Now the performance is much steadier than before
2.	Now increasing JVM’s memory will not bring much performance improvement.

**Comment by clockfly** [comment]
Great!
