### ISSUE TITLE
Investigate on Akka-persistence as a general storage implementation

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1822]
Motive:
Currently we use replicated memory to store some data, it has risks when the whole cluster is brought down due to power failure.

We need to investigate wether Akka-persistence can be used as a distributed, pluggable, general storage to persist data like:
1. application timestamp
2. application submission info (like jar, and confgs...)
3. application runtime storage for KV. 

What is the expected output for this investigation:
We expect to see a test project in scala which use "akka persistence", it should:
1. provide a API to read/write large chunk of data in a streaming way, suggest to test it on Tested on HDFS, and Redis.
2. connect with akka-data-replication to persist the CRDT data, and why this can still be consistent?
3. Demo how this can be plugged, how to switch between HDFS and Redis. What is the new classpath introduced for each storage(HDFS or Redis)?

**Comment by clockfly** [comment]
This is related with https://github.com/gearpump/gearpump/issues/1197

**Comment by manuzhang** [comment]
From http://www.slideshare.net/ktoso/zen-of-akka/31, 

> If you want a raw key-value store, and don't want Event Sourcing capabilities, don't use Akka Persistence.

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-66. @netcomm, you may continue your work on that jira.
