### ISSUE TITLE
After killing all worker instances, application status should not be described as active

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1825]
Step to reproduce:

1. Start cluster with one worker
2. Start a word count
3. Kill the worker

Expect `/api/v1.0/master/applist` actually returns app status as `active`, but application's detail page is not available. I think as there is no resource to run the application, the application is in some abnormal status. In order not to mislead user, I think we should invent a new status, might be `recovering` or something.

Example output:
```
{"appMasters":[{"status":"active","appId":1,"appName":"dag","appMasterPath":"akka.tcp://app1-executor-1@127.0.0.1:46761/user/daemon/appdaemon1/$c","workerPath":"akka.tcp://48a47aa6-81c0-493c-9948-9d7d4c946db6@127.0.0.1:59201/user/Worker48a47aa6-81c0-493c-9948-9d7d4c946db6","submissionTime":"1451894551477","startTime":"1451894553568","user":"qxu"},{"status":"active","appId":2,"appName":"wordCount","appMasterPath":"akka.tcp://app2-executor-1@127.0.0.1:49261/user/daemon/appdaemon2/$c","workerPath":"akka.tcp://48a47aa6-81c0-493c-9948-9d7d4c946db6@127.0.0.1:59201/user/Worker48a47aa6-81c0-493c-9948-9d7d4c946db6","submissionTime":"1451898038991","startTime":"1451898040265","user":"qxu"}]}
```

**Comment by kkasravi** [comment]
Moved to JIRA. See https://issues.apache.org/jira/browse/GEARPUMP-83
