### ISSUE TITLE
Support Page Visibility API

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1826]
Story:
1. When the dashboard is visible to user, then the javascript in the backend should send active REST queries.
2. When the dashboard is not visible, then the javascript should not send REST query to backend.

This will save resource both for frontend browser, and for backend server. It also saves network bandwidth. 

The good news is that we have visibility API: [Doc](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?redirectlocale=en-US&redirectslug=DOM%2FUsing_the_Page_Visibility_API)
jquery plugin: [JQuery plugin](https://github.com/mathiasbynens/jquery-visibility)
Here is an example: [Code Example](https://mathiasbynens.be/demo/jquery-visibility)

**Comment by stanleyxu2005** [comment]
Interesting. I believe for bandwidth sensitive environment, using websocket can save more bandwidth.

**Comment by kkasravi** [comment]
it seems like there is good websocket support in akka-streams. From past experience with websockets I would also recommend this transition. Note: both approaches are possible. One concern is page visibility is that once visible we may need to request a large range of values and there may be a short delay before this data is correctly displayed.

**Comment by clockfly** [comment]
Sleep this for low priority.
