### ISSUE TITLE
update Gearpump's performance metrics in doc

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1833]

**Comment by darionyaphet** [comment]
I hava a silly question : How to add label ? thank you ~~

**Comment by huafengw** [comment]
If you mean **add**:
![capture2](https://cloud.githubusercontent.com/assets/5011399/12109382/5ab6e4bc-b3bc-11e5-8684-f4aacb918f6f.PNG)


Or **apply** a label:
![capture](https://cloud.githubusercontent.com/assets/5011399/12109388/6d2b0376-b3bc-11e5-8490-2b7c7733087d.PNG)
