### ISSUE TITLE
Minimum clock of source Tasks maybe inaccurate

### ISSUE THREAD

**Issue by yueqianzhu** [gearpump/gearpump#1835]
Source tasks have not any upstreamClocks. So, startClock is the minimum of pending clocks when recover happen.

eg below:
source task1: timeStamp:15,not ACK, minClockValue maybe is 15(<= 15).
source task2: timeStamp:10,ACKed, minClockValue maybe is Long.MaxValue
when recover happen,startClock maybe is 15.  where is the data between 10 to 15 at task2?

**Comment by clockfly** [comment]
@yueqianzhu 

Thanks for reporting.

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-32
