### ISSUE TITLE
bin/local  is unexecutable

### ISSUE THREAD

**Issue by zhaosoap** [gearpump/gearpump#1842]
I've found bin/local is unexecutable after 'sbt clean assembly packArchiveZip'.

**Comment by manuzhang** [comment]
Hi, you need to `chmod +x bin/*` to make it executable as documented [here](http://www.gearpump.io/releases/latest/deployment-local.html#step-2-start-the-cluster)

**Comment by stanleyxu2005** [comment]
@manuzhang I think sbt script should do `chmod +x bin/*`

**Comment by manuzhang** [comment]
Whether a file is executable depends on different users on different systems. We cannot enforce that.

**Comment by darionyaphet** [comment]
`Sbt` is a tool to compile source code and package as released . Maybe can't make scripts executable .

**Comment by manuzhang** [comment]
hi @zhaosoap, any update on this issue ?

**Comment by manuzhang** [comment]
@zhaosoap I'm closing this. Please open an jira at https://issues.apache.org/jira/browse/GEARPUMP if you still find this is an issue.
