### ISSUE TITLE
Launch and kill a worker or master

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1843]
Privileged person should have the ability add a new worker (or a master) or kill a running worker (or a master) via REST api.

**Comment by kkasravi** [comment]
@stanleyxu2005 @clockfly Logic would be tied to YARN currently but we should try and make this pluggable or at least hide YARN explicit references?

**Comment by stanleyxu2005** [comment]
I think we can create follow-up issue to hide YARN explicit reference

**Comment by stanleyxu2005** [comment]
@kkasravi I accidentally tried the feature on a non-YARN environment. The error message is a `TimeoutException`. I have a question: how the client (dashboard) is able to know, whether the environment is YARN or standalone?

**Comment by kkasravi** [comment]
i'll open an issue for this. I believe the -supervisor option indicates YARN, but I'll confirm.

**Comment by stanleyxu2005** [comment]
Yes, it needs a rest api to indicate the environment. it can be a section of the api of querying master, or an individual api.

**Comment by stanleyxu2005** [comment]
When I want to delete a worker, I should call `POST /api/v1.0/supervisor/removeworker/$uripath`, What is the `$uripath` for worker 0? Is it the actor path or the worker id or something else?
