### ISSUE TITLE
REST API documentation is not comprehensive (and should be autogenerated)

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1849]
See http://www.gearpump.io/releases/latest/dev-rest-api.html which does not include for example the POST /api/v1.0/master/submitdag

We should consider swagger or something similar

**Comment by kkasravi** [comment]
Current REST API should be defined using https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md.

**Comment by clockfly** [comment]
Superseded by PR https://github.com/gearpump/gearpump/pull/2023
