### ISSUE TITLE
update sbt to 0.13.9

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1852]
It has bunch of fixes in cache resolution,
https://github.com/sbt/sbt/releases

**Comment by darionyaphet** [comment]
I think `sbt` is not very clearly for reading and maintain `gradle` is a better choice ?

**Comment by clockfly** [comment]
@darionyaphet 

I agree with you that sbt is harder to use. The current situation is that there are some handy plugin which save us a lot of time to maintain the package:
1. Plugin "sbt-pack". It can automatically generate different format of script like bat or sh for different OS automatically. it can also generate a distribution package, like the gearpump-x.zip gearpump-x.tar.gz you see.
2. Plugin "sbt-unidoc". It will consolidate scala doc from different projects together into a unified one. With this, we can easily publish our doc on http://gearpump.io
3. cross build. As you know, sbt hide the scala version like 2.10 and 2.11 from "artifact", and it is also very easy to do cross-build for different OS.

**Comment by clockfly** [comment]
fixed in #1857
