### ISSUE TITLE
UI will try to reconnect to backend in a dead loop with no interval

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1855]
When the backend UI server is down, the frontend will aggressively query the backend service, even though there is "failure"

In my machine, there are 67 backend calls in 30 seconds. 
Looks like it is a dead loop without setting retry interval. 

I think the same interval setting should applies (3 seconds) no matter it can or cannot access to backend UI.

**Comment by stanleyxu2005** [comment]
I think this issue is somehow linked to https://github.com/gearpump/gearpump/issues/1855
