### ISSUE TITLE
IP Clearence

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1860]
### Source dependencies:
1.	docs/js/vendor/bootstrap-3.3.5.min.js, MIT license
2.	docs/js/vendor/jquery-2.1.4.min.js, MIT license
3.	docs/js/vendor/ modernizr-2.6.1-respond-1.1.0.min.js, Dual MIT/BSD license
4.	services/dashboard/style/bootstrap-doc.css, Creative Commons Attribution 3.0

### Binary dependencies:
[ipPlan.xlsx](https://github.com/gearpump/gearpump/files/89909/ipPlan.xlsx)

|                                                 |                                 |                                                                                        | 
|-------------------------------------------------|---------------------------------|----------------------------------------------------------------------------------------| 
| Binary shipped in the release package           | License                         | License link                                                                           | 
| activation-1.1.jar                              | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-actor_2.11-2.3.12-fix-1816.jar             | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-agent_2.11-2.3.12.jar                      | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-cluster_2.11-2.3.12.jar                    | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-contrib_2.11-2.3.12.jar                    | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-data-replication_2.11-0.7.jar              | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-http-core-experimental_2.11-1.0.jar        | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-http-experimental_2.11-1.0.jar             | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-http-session_2.11-0.1.4.jar                | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-http-spray-json-experimental_2.11-1.0.jar  | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-kernel_2.11-2.3.12.jar                     | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-parsing-experimental_2.11-1.0.jar          | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-remote_2.11-2.3.12.jar                     | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-slf4j_2.11-2.3.12.jar                      | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| akka-stream-experimental_2.11-1.0.jar           | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| angular-1.5.0-rc.0.jar                          | MIT                             | https://github.com/angular/angular.js/blob/master/LICENSE                              | 
| angular-loading-bar-0.8.0.jar                   | MIT                             | https://github.com/chieffancypants/angular-loading-bar/blob/master/LICENSE             | 
| angular-motion-0.4.3.jar                        | MIT                             | https://github.com/mgcrea/angular-motion/blob/master/LICENSE.md                        | 
| angular-smart-table-2.1.6.jar                   | MIT                             | https://github.com/lorenzofox3/Smart-Table                                             | 
| angular-strap-2.3.5.jar                         | MIT                             | https://github.com/mgcrea/angular-strap/blob/master/LICENSE.md                         | 
| angular-ui-router-0.2.15.jar                    | MIT                             | https://github.com/angular-ui/ui-router/blob/master/LICENSE                            | 
| angular-ui-select-0.13.2.jar                    | MIT                             | https://github.com/angular-ui/ui-select/blob/master/LICENSE                            | 
| angularjs-1.4.8.jar                             | MIT                             | https://github.com/angular/angular.js/blob/master/LICENSE                              | 
| aopalliance-1.0.jar                             | Public Domain.                  | http://aopalliance.sourceforge.net/                                                    | 
| apacheds-i18n-2.0.0-M15.jar                     | Apache                          | Apache Foundation                                                                      | 
| apacheds-kerberos-codec-2.0.0-M15.jar           | Apache                          | Apache Foundation                                                                      | 
| api-asn1-api-1.0.0-M20.jar                      | Apache                          | Apache Foundation                                                                      | 
| api-util-1.0.0-M20.jar                          | Apache                          | Apache Foundation                                                                      | 
| asm-3.1.jar                                     |                                 | http://asm.ow2.org/license.html                                                        | 
| avro-1.7.6-cdh5.4.2.jar                         | Apache                          | Apache Foundation                                                                      | 
| bootstrap-3.3.6.jar                             | MIT                             | https://github.com/twbs/bootstrap/blob/master/LICENSE                                  | 
| bootstrap-additions-0.3.1.jar                   | MIT                             | https://github.com/twbs/bootstrap/blob/master/LICENSE                                  | 
| carbonite-1.4.0.jar                             | Apache compatible               | https://clojars.org/com.twitter/carbonite                                              | 
| cglib-2.2.1-v20090111.jar                       | Apache                          | http://cglib.sourceforge.net/license.html                                              | 
| chill-java-0.3.5.jar                            | Apache                          | https://github.com/twitter/chill/blob/develop/LICENSE                                  | 
| clipboard.js-0.1.1.jar                          | MIT                             | https://zenorocha.github.io/clipboard.js/                                              | 
| clojure-1.5.1.jar                               | Eclipse public domain           | http://clojure.org/WVTkO/KWcKM/license                                                 | 
| commons-beanutils-1.7.0.jar                     | Apache                          | Apache Foundation                                                                      | 
| commons-beanutils-core-1.8.0.jar                | Apache                          | Apache Foundation                                                                      | 
| commons-cli-1.2.jar                             | Apache                          | Apache Foundation                                                                      | 
| commons-codec-1.4.jar                           | Apache                          | Apache Foundation                                                                      | 
| commons-codec-1.6.jar                           | Apache                          | Apache Foundation                                                                      | 
| commons-collections-3.2.1.jar                   | Apache                          | Apache Foundation                                                                      | 
| commons-compress-1.4.1.jar                      | Apache                          | Apache Foundation                                                                      | 
| commons-configuration-1.6.jar                   | Apache                          | Apache Foundation                                                                      | 
| commons-daemon-1.0.13.jar                       | Apache                          | Apache Foundation                                                                      | 
| commons-digester-1.8.jar                        | Apache                          | Apache Foundation                                                                      | 
| commons-el-1.0.jar                              | Apache                          | Apache Foundation                                                                      | 
| commons-exec-1.1.jar                            | Apache                          | Apache Foundation                                                                      | 
| commons-fileupload-1.2.1.jar                    | Apache                          | Apache Foundation                                                                      | 
| commons-httpclient-3.1.jar                      | Apache                          | Apache Foundation                                                                      | 
| commons-io-2.4.jar                              | Apache                          | Apache Foundation                                                                      | 
| commons-lang-2.6.jar                            | Apache                          | Apache Foundation                                                                      | 
| commons-logging-1.1.3.jar                       | Apache                          | Apache Foundation                                                                      | 
| commons-math3-3.1.1.jar                         | Apache                          | Apache Foundation                                                                      | 
| commons-net-3.1.jar                             | Apache                          | Apache Foundation                                                                      | 
| config-1.2.1.jar                                | Apache2                         | http://doc.akka.io/docs/akka/snapshot/project/licenses.html                            | 
| curator-client-2.7.1.jar                        | Apache                          | Apache Foundation                                                                      | 
| curator-framework-2.7.1.jar                     | Apache                          | Apache Foundation                                                                      | 
| curator-recipes-2.7.1.jar                       | Apache                          | Apache Foundation                                                                      | 
| d3js-3.5.6.jar                                  | BSD                             | http://d3js.org/                                                                       | 
| dashing-0.4.0.jar                               | Apache                          | Intel employee maintained project                                                      | 
| dashing-deps-0.1.2.jar                          | Apache                          | Intel employee maintained project                                                      | 
| derive_2.11-0.3.4.jar                           | MIT                             | https://lihaoyi.github.io/upickle-pprint/upickle/#MITLicense                           | 
| disruptor-2.10.1.jar                            | Apache                          | https://github.com/LMAX-Exchange/disruptor/blob/master/LICENCE.txt                     | 
| font-awesome-4.5.0.jar                          |  font:SIL OFL 1.1 css code: MIT | https://fortawesome.github.io/Font-Awesome/license/                                    | 
| gson-2.2.4.jar                                  | Apache                          | https://github.com/google/gson/blob/master/LICENSE                                     | 
| guava-11.0.2.jar                                | Apache                          | https://code.google.com/p/guava-libraries/                                             | 
| guice-3.0.jar                                   | Apache 2.0                      | https://github.com/google/guice                                                        | 
| guice-servlet-3.0.jar                           | Apache 2.0                      | https://github.com/google/guice                                                        | 
| hadoop-annotations-2.6.0-cdh5.4.2.jar           | Apache                          | Apache Foundation                                                                      | 
| hadoop-auth-2.6.0-cdh5.4.2.jar                  | Apache                          | Apache Foundation                                                                      | 
| hadoop-common-2.6.0-cdh5.4.2.jar                | Apache                          | Apache Foundation                                                                      | 
| hadoop-hdfs-2.6.0-cdh5.4.2.jar                  | Apache                          | Apache Foundation                                                                      | 
| hadoop-mapreduce-client-core-2.6.0-cdh5.4.2.jar | Apache                          | Apache Foundation                                                                      | 
| hadoop-yarn-api-2.6.0-cdh5.4.2.jar              | Apache                          | Apache Foundation                                                                      | 
| hadoop-yarn-client-2.6.0-cdh5.4.2.jar           | Apache                          | Apache Foundation                                                                      | 
| hadoop-yarn-common-2.6.0-cdh5.4.2.jar           | Apache                          | Apache Foundation                                                                      | 
| htrace-core-3.0.4.jar                           | Apache                          | https://github.com/cloudera/htrace/blob/master/LICENSE.txt                             | 
| httpclient-4.2.5.jar                            | Apache                          | Apache Foundation                                                                      | 
| httpcore-4.2.4.jar                              | Apache                          | Apache Foundation                                                                      | 
| jackson-core-asl-1.8.8.jar                      | Apache                          | http://wiki.fasterxml.com/JacksonLicensing                                             | 
| jackson-jaxrs-1.8.8.jar                         | Apache                          | http://wiki.fasterxml.com/JacksonLicensing                                             | 
| jackson-mapper-asl-1.8.8.jar                    | Apache                          | http://wiki.fasterxml.com/JacksonLicensing                                             | 
| jackson-xc-1.8.8.jar                            | Apache                          | http://wiki.fasterxml.com/JacksonLicensing                                             | 
| jasper-compiler-5.5.23.jar                      | Apache                          | Apache Foundation                                                                      | 
| jasper-runtime-5.5.23.jar                       | Apache                          | Apache Foundation                                                                      | 
| java-xmlbuilder-0.4.jar                         | Apache                          | https://github.com/jmurty/java-xmlbuilder/blob/master/LICENSE-2.0.txt                  | 
| javax.inject-1.jar                              | oracle                          | oracle java                                                                            | 
| jawn-parser_2.11-0.7.0.jar                      | MIT                             | https://github.com/non/jawn                                                            | 
| jaxb-api-2.2.2.jar                              | ?CDDL                           | https://jaxb.java.net/                                                                 | 
| jaxb-impl-2.2.3-1.jar                           | ?CDDL                           | https://jaxb.java.net/                                                                 | 
| jersey-client-1.9.jar                           | CDDL                            | https://jersey.java.net/license.html                                                   | 
| jersey-core-1.9.jar                             | CDDL                            | https://jersey.java.net/license.html                                                   | 
| jersey-guice-1.9.jar                            | CDDL                            | https://jersey.java.net/license.html                                                   | 
| jersey-json-1.9.jar                             | CDDL                            | https://jersey.java.net/license.html                                                   | 
| jersey-server-1.9.jar                           | CDDL                            | https://jersey.java.net/license.html                                                   | 
| jets3t-0.9.0.jar                                | Apache                          | http://www.jets3t.org/                                                                 | 
| jettison-1.1.jar                                | Apache                          | https://svn.apache.org/repos/asf/axis/axis2/java/core/trunk/legal/jettison-LICENSE.txt | 
| jetty-6.1.26.cloudera.4.jar                     | Apache                          | http://www.eclipse.org/jetty/licenses.php                                              | 
| jetty-util-6.1.26.cloudera.4.jar                | Apache                          | http://www.eclipse.org/jetty/licenses.php                                              | 
| jgrapht-core-0.9.0.jar                          | EPL                             | https://github.com/jgrapht/jgrapht/blob/master/license-EPL.txt                         | 
| jline-0.9.94.jar                                | BSD                             | http://jline.sourceforge.net/license.html                                              | 
| jquery-2.2.0.jar                                | MIT                             | https://jquery.org/license/                                                            | 
| jquery-cookie-1.4.1.jar                         | MIT                             | https://github.com/carhartl/jquery-cookie/blob/master/MIT-LICENSE.txt                  | 
| jsch-0.1.42.jar                                 | BSD                             | http://www.jcraft.com/jsch/LICENSE.txt                                                 | 
| json-simple-1.1.jar                             | Apache                          | http://code.google.com/p/json-simple/                                                  | 
| jsp-api-2.1.jar                                 | oracle                          | oracle java                                                                            | 
| jsr305-3.0.0.jar                                | bsd                             | https://code.google.com/p/jsr-305/source/browse/trunk/ri/LICENSE                       | 
| kryo-2.21.jar                                   | BSD                             | https://code.google.com/p/kryo/                                                        | 
| leveldbjni-all-1.8.jar                          | BSD                             | https://github.com/fusesource/leveldbjni                                               | 
| lodash-3.10.1.jar                               | MIT                             | https://lodash.com/license                                                             | 
| log4j-1.2.17.jar                                | Apache                          | Apache Foundation                                                                      | 
| minlog-1.2.jar                                  | BSD                             | https://github.com/EsotericSoftware/minlog/blob/master/license.txt                     | 
| momentjs-2.10.6.jar                             | MIT                             | https://github.com/assisrafael/angular-momentjs/blob/master/LICENSE                    | 
| netty-3.8.0.Final.jar                           | Apache                          | netty.io                                                                               | 
| ng-file-upload-5.0.9.jar                        | MIT                             | https://github.com/danialfarid/ng-file-upload/blob/master/LICENSE                      | 
| objenesis-1.2.jar                               | Apache                          | http://objenesis.org/license.html                                                      | 
| paranamer-2.3.jar                               | BSD                             | https://github.com/paul-hammant/paranamer                                              | 
| protobuf-java-2.5.0.jar                         | BSD                             | https://github.com/google/protobuf/blob/master/LICENSE                                 | 
| reactive-streams-1.0.0.jar                      | Public Domain                   | https://github.com/reactive-streams/reactive-streams-jvm/blob/master/LICENSE           | 
| reflectasm-1.07-shaded.jar                      | BSD                             | https://github.com/EsotericSoftware/reflectasm                                         | 
| scala-library-2.11.5.jar                        | scala license                   | http://www.scala-lang.org/license.html                                                 | 
| scala-library-2.11.6.jar                        | scala license                   | http://www.scala-lang.org/license.html                                                 | 
| scala-parser-combinators_2.11-1.0.3.jar         | scala license                   | http://www.scala-lang.org/license.html                                                 | 
| scala-reflect-2.11.5.jar                        | scala license                   | http://www.scala-lang.org/license.html                                                 | 
| scala-stm_2.11-0.7.jar                          | scala license                   | http://www.scala-lang.org/license.html                                                 | 
| servlet-api-2.5.jar                             | Apache                          | Apache Foundation                                                                      | 
| slf4j-api-1.7.7.jar                             | Apache                          | Apache Foundation                                                                      | 
| slf4j-log4j12-1.7.7.jar                         | Apache                          | Apache Foundation                                                                      | 
| snakeyaml-1.11.jar                              | Apache                          | https://code.google.com/p/snakeyaml/                                                   | 
| snappy-java-1.0.5.jar                           | Apache                          | https://github.com/xerial/snappy-java/blob/develop/LICENSE                             | 
| spray-json_2.11-1.3.1.jar                       | Apache                          | https://github.com/spray/spray-json/blob/master/LICENSE                                | 
| stax-api-1.0-2.jar                              | BSD                             | https://github.com/FasterXML/stax2-api                                                 | 
| storm-core-0.9.5.jar                            | Apache                          | Apache Foundation                                                                      | 
| uncommons-maths-1.2.2a.jar                      | Apache                          | http://maths.uncommons.org/                                                            | 
| upickle_2.11-0.3.4.jar                          | MIT                             | https://lihaoyi.github.io/upickle-pprint/upickle/#MITLicense                           | 
| vis-4.7.0.jar                                   | Apache                          | http://visjs.org/#licenses                                                             | 
| xmlenc-0.52.jar                                 | MIT                             | https://github.com/digidentity/xmlenc/blob/master/LICENSE.txt                          | 
| xz-1.0.jar                                      | public domain                   | http://tukaani.org/xz/java.html                                                        | 
| zookeeper-3.4.6.jar                             | Apache                          | Apache Foundation                                                                      | 
| Echarts?                                        | baidu license                   | https://github.com/ecomfe/echarts/blob/master/LICENSE                                  |

**Comment by stanleyxu2005** [comment]
echarts is a resolved in dashing-deps. Itself is Baidu License.

**Comment by clockfly** [comment]
Solved. The Software grant has been issued to Apache foundation.
