### ISSUE TITLE
should dag's node size be measured by receive throughput?

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1861]
For a DataSource processor, it is very common that it will continually send drive message to itself while actually the processor does not output so many messages to the downstream processor. So the dag may look like:
![capture](https://cloud.githubusercontent.com/assets/5011399/12316550/d899ef16-bac2-11e5-8f0e-b8e4ca0cbf86.PNG)
Then the downstream node is kind of hard to choose.
Can we measure the node's size by its send throughput and for a sink processor by its receive throughput?

**Comment by stanleyxu2005** [comment]
Currently the weight is calculated by the average of "send throughput rate" and "receive throughput rate". Yes, I got your point. I think for source processor we can use "send throughput rate"; for sink processor we can use "receive throughput rate"; and for general processor we still use the average of both rates.

**Comment by stanleyxu2005** [comment]
@huafengw  Shall we close this issue?
