### ISSUE TITLE
dependency conflicts between storm applications and daemon 

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1871]
Unlike other Gearpump applications, Storm application could contain a bunch of third-side dependencies, which could easily have conflicts with daemon classpath. The daemon classpath includes a lot of dependencies from yarn.

**Comment by clockfly** [comment]
Why storm module need to depends on daemon?

**Comment by manuzhang** [comment]
for DFSJarStore ?
```
  val stormClassPath = daemonClassPath ++ Seq(
    "${PROG_HOME}/lib/storm/*"
  )
```

**Comment by clockfly** [comment]
Checked with @manuzhang 

This is no longer a problem. Now we use a standalone nimbus service.
