### ISSUE TITLE
Login failure results in unparsed html error 

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1874]
See below

![screen shot 2016-01-16 at 1 11 39 pm](https://cloud.githubusercontent.com/assets/146453/12379041/4c4a6d1a-bd06-11e5-8cb6-3f6ed61e041e.png)

**Comment by clockfly** [comment]
This is the problem of YARN UI Proxy, It use a full html page as error response instead of a text mime. With Yarn UI Proxy, it looks fine like this:
```
error(401): The resource requires authentication, which was not supplied with the request
```

Since we cannot possiblly render "html", "head" "title" in a div, and it is not safe to do that. Will mark this as won't fix.

**Comment by clockfly** [comment]
This is the problem of YARN UI Proxy, It use a full html page as error response instead of a text mime. Without Yarn UI Proxy, it looks fine like this:
```
error(401): The resource requires authentication, which was not supplied with the request
```

Since we cannot possiblly render "html", "head" "title" in a div, and it is not safe to do that. Will mark this as won't fix.

**Comment by stanleyxu2005** [comment]
Can you capture the HTTP 405 before rendering the page?

**Comment by clockfly** [comment]
I apologize for closing this, thank you for stanley pointing out a good solution.
