### ISSUE TITLE
Launching YARN appmaster from yarnclient sometimes results in failed master, worker

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1875]
See screen shot

![screen shot 2016-01-17 at 11 04 11 am](https://cloud.githubusercontent.com/assets/146453/12379205/50f91164-bd0a-11e5-83cc-0812f59aac21.png)

**Comment by clockfly** [comment]
Do you mean rest api fails? Or mean worker node is down?

**Comment by whjiang** [comment]
Is it possible this bug is similar to the one we found in IntegrationTest cluster startup? That is, the master start up slow caused the YARNClient fail to connect?

**Comment by kkasravi** [comment]
REST API shows no master or worker. Yes this could be related to slow master startup. I'll check and see if master is actually running next time I see it.

**Comment by kkasravi** [comment]
unable to reproduce
