### ISSUE TITLE
Will io.gearpump.streaming.task.TaskContext#schedule break the thread-safety of a Task?

### ISSUE THREAD

**Issue by Renkai** [gearpump/gearpump#1881]
By default,there would be only one thread runinng in the Task(or actor) code one time,but schedule may cause another thread run simultaneously.

I think 
```
    taskContext.schedule(xx,xx) {
      self ! SomeMassage
    }
```
is a good way to avoid concurrency problems,however in the comment there is 
```
  /**
   * Please don't use this if possible.
   * @return  self actor ref
   */
  //TODO: We should remove the self from TaskContext
```
So what should I do when  I want to do some schedule work and avoid concurrency problems in a Task?

**Comment by manuzhang** [comment]
No, `schedule` will not break the thread-safety. Task code is always executed by one thread at a time and you can see the code in `schedule` as another task. They are just like two tasks being executed by configured `gearpump.task-dispatcher`.

**Comment by Renkai** [comment]
I mean in some code schedule and onNext may share memory like below

```scala
class MayThrowException(taskContext: TaskContext, conf: UserConfig) extends Task(taskContext, conf) {
  private var scheduler: Cancellable = null

  val cache: mutable.HashMap[String, Long] = new mutable.HashMap[String, Long]()

  override def onStart(startTime: StartTime): Unit = {
    scheduler = taskContext.schedule(new FiniteDuration(5, TimeUnit.SECONDS),
      new FiniteDuration(30, TimeUnit.SECONDS)) {
      cache.clear()
    }
  }

  override def onNext(msg: Message): Unit = {
    msg.msg match {
      case (x: String, y: Int) => cache.put(x, y)
    }
  }
}
```
would it throw a ConcurrentModificationException?

**Comment by manuzhang** [comment]
Yes, we should avoid shared mutable state. Sending message to `self` is ok if you have to.

**Comment by manuzhang** [comment]
Hi @Renkai , is this issue solved for you ?
