### ISSUE TITLE
Improve the UI experience

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1892]
These important functions in UI can be easily overlooked, due to the UI design:
1. Compose the DAG. User can compose the application by drag and drop in UI.
2. Change parallelism in DAG canvas. User can change the parallelism in runtime without message loss.
3. Replace DAG in DAG canvas, user can replace partial nodes of the DAG, without impacting upstream and downstream nodes. 

We should do some improvement to change it.

![ui_improve](https://cloud.githubusercontent.com/assets/2595532/12414275/695eaa36-becf-11e5-9467-48e425612687.jpg)

**Comment by stanleyxu2005** [comment]
I think this is more like an improvement or a feature request rather than a bug. I'd add a text description to tell that user can tap a node to see more actions.
