### ISSUE TITLE
Improvements in REST API for addmaster, addworker, removemaster, removeworker

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1893]
This may be an umbrella task

- [x] Right now the only way to remove a worker is to specify a YARN containerId. We should allow different query parameters other than containerId such as workerId and remove the path specification
- [x] CommandStatus provides an exception as a string. This should be a subclass of Throwable so we can potentially use status codes based on exception subclass
- [x] When removing a YARN container (removemaster, removeworker) - we may want to send messages to the executors that they are about to be terminated (or have the worker do so) or not remove workers if they have active executors

**Comment by stanleyxu2005** [comment]
@kkasravi Regarding #1997, do you think we can close this issue?

**Comment by clockfly** [comment]
fixed.
