### ISSUE TITLE
Some SAMOA tasks failed running on gearpump

### ISSUE THREAD

**Issue by pangolulu** [gearpump/gearpump#1901]
I try to run some SAMOA tasks on gearpump, but I find that I even can't submit my app successfully, it just stuck there. And I can't find "applicationData" directory in the "logs" directory. Are there any logs or error outputs if my app isn't submitted successfully?

The topology of these tasks are as follow:
![image](https://cloud.githubusercontent.com/assets/5796671/12442445/f7e0bb58-bf8a-11e5-80fe-0d306663c618.png)

Does it because it contains a circle in the graph?

And I find my task like as the following topology is successfully run.
![capture](https://cloud.githubusercontent.com/assets/5796671/12442563/de13bcc4-bf8b-11e5-8d71-fbb98f89d5d8.PNG)

**Comment by manuzhang** [comment]
try submitting with  `-verbose` and that would give you some error info

**Comment by huafengw** [comment]
I think now Gearpump will check the submitted DAG, if it contains a cycle, something will go wrong.

**Comment by pangolulu** [comment]
The main method is:
```
public static void main(String[] args) {
        Topology topology = Utils.argsToTopology(args);
        String topologyName = topology.getTopologyName();
        io.gearpump.util.Graph graph = topology.getGraph();
        StreamApplication app = StreamApplication.apply(topologyName, graph, UserConfig.empty());
        ClientContext context = ClientContext.apply();
        context.submit(app);
        context.close();
        logger.info("Success in submitting app!");
    }
```

I have logged step-by-step, and it stuck at:
```
StreamApplication app = StreamApplication.apply(topologyName, graph, UserConfig.empty());
ClientContext context = ClientContext.apply();
context.submit(app);
context.close();
```

Output of logs are:
![image](https://cloud.githubusercontent.com/assets/5796671/12443507/335bd66a-bf93-11e5-8099-7610878c7823.png)
