### ISSUE TITLE
Some dashing library bugs.

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1906]
Problems:
1. The last time form control is not aligned.
2. The calendar and time popup cannot be displayed on mobile.
3. the compose DAG, new partitioner dialog, cannot select a processor.

![dashing](https://cloud.githubusercontent.com/assets/2595532/12453050/6d14e8ae-bfcc-11e5-9e77-88c5b2283f9d.jpg)

![onedge](https://cloud.githubusercontent.com/assets/2595532/12453106/aafd328e-bfcc-11e5-90e3-5c9f0dc8261c.jpg)

**Comment by stanleyxu2005** [comment]
Regarding the 2nd problem. I use native date/time picker on mobile device. It works so far for iPhone. Did you see the problem on a real mobile phone, or only in Chrome's emulator?
