### ISSUE TITLE
Provide time window DSL and standard deviation

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1917]
Other frameworks such as bean, flink, spark provide time window based DSL's that allow fixed, sliding, tumbling and other types of time window processing. We should provide parity with these types of frameworks since time series processing is very common. See several comparisons:

https://databaseline.files.wordpress.com/2016/03/stream-processing-technologies.png
https://docs.google.com/spreadsheets/d/1OM077lZBARrtUi6g0X0O0PHaIbFKCD6v0djRefQRE1I/edit#gid=939018601

Additional articles are also noted below

**Comment by kkasravi** [comment]
## Features

Different types of windows should be provided that included different processing times: 

## event time

## processor time 

## ingestion time.

The DSL should do provide a TimeOp which allows different TimeFunctions to be added to the Stream DAG. These TimeFunctions could be

## TimeValue(duration Duration)

## TimeRange(start Date, end Date)

Time values would be collected under a List until the times bounds are satisfied.

**Comment by clockfly** [comment]
Thanks for putting these together.

**Comment by kkasravi** [comment]
A few articles for reference which may be valuable
1. [Flink's API and implementation](https://flink.apache.org/news/2015/12/04/Introducing-windows.html)
2. [DataFlow, Spark API comparison](https://cloud.google.com/dataflow/blog/dataflow-beam-and-spark-comparison)

**Comment by kkasravi** [comment]
Moved to JIRA - see https://issues.apache.org/jira/browse/GEARPUMP-23
