### ISSUE TITLE
command option -verbose does not have effect on output

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1928]
Whether it's true or not, the outputs of the command have no difference.

**Comment by manuzhang** [comment]
Do we want `log4j.rootLevel=INFO` or `log4j.rootLevel=ERROR` ?

**Comment by manuzhang** [comment]
And this doesn't look right. "DEBUG" is not verbose.
```scala
  def verboseLogToConsole: Unit = {
    val props = loadConfiguration
    props.setProperty("log4j.rootLogger", "DEBUG,console")
    PropertyConfigurator.configure(props)
  }
```

**Comment by manuzhang** [comment]
verbose does have effect by turning on DEBUG log level. The problem is we have too many INFO level logs.
