### ISSUE TITLE
Integrate gearpump into zeppelin

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1930]
Similar to what flink has done
https://cwiki.apache.org/confluence/display/ZEPPELIN/Zeppelin+Roadmap

**Comment by clockfly** [comment]
+1

**Comment by darionyaphet** [comment]
+1

**Comment by kkasravi** [comment]
Moved to JIRA. See https://issues.apache.org/jira/browse/GEARPUMP-56
