### ISSUE TITLE
client config overwrites critical system config

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1932]
1. Critical system configs (e.g. `gearpump.home`) should not be allowed to be overwritten by client submission config
2. application config shown on UI is not the final merged configs

**Comment by manuzhang** [comment]
| config |
| -------- |
| gearpump.task-dispatcher |
| gearpump.metrics.enabled |
| gearpump.metrics.sample-rate | 
| gearpump.metrics.report-interval-ms |
| gearpump.metrics.reporter | 
| gearpump.retainHistoryData.hours | 
| gearpump.retainHistoryData.intervalMs |
| gearpump.retainRecentData.intervalMs |
| gearpump.log.application.dir	|
| gearpump.serializers |
| gearpump.serialization-framework	| 
| gearpump.appmaster.vmargs | 
| gearpump.appmaster.extraClasspath |
| gearpump.executor.vmargs | 
| gearpump.executor.extraClasspath | 
| gearpump.scheduling.scheduler-class | 
| gearpump.netty.buffer-size |
| gearpump.netty.max-retries |
| gearpump.netty.base-sleep-ms |
| gearpump.netty.max-sleep-ms |
| gearpump.netty.message-batch-size |
| gearpump.netty.flush-check-interval |
| gearpump.netty.dispatcher |
| gearpump.shared-thread-pool-dispatcher | 
| gearpump.single-thread-dispatcher |
| gearpump.remote-debug-executor-jvm |
| gearpump.remote-debug-port | 
| gearpump.verbose-gc |
| gearpump.streaming.register-task-timeout-ms |
| gearpump.streaming.ack-once-every-message-count |
| gearpump.streaming.max-pending-message-count-per-connection |

**Comment by clockfly** [comment]
@manuzhang 

Can we use a black list instead of white list? We cannot predict what custom config client may create.
