### ISSUE TITLE
Propose to rename supervisor apis

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1939]
@kkasravi 

Add worker should be 
`POST /api/v1.0/supervisor/worker` not `POST /api/v1.0/supervisor/addworker/$count`

Add master should be
`POST /api/v1.0/supervisor/master` not `POST /api/v1.0/supervisor/addmaster`

Remove a resource should use DELETE instead of POST.

Remove worker should be
`DELETE /api/v1.0/supervisor/worker/$workerId` not `POST /api/v1.0/supervisor/removeworker/$uripath`

Remove master should be
`DELETE /api/v1.0/supervisor/master/$uripath` not `POST /api/v1.0/supervisor/removemaster/$uripath`

**Comment by kkasravi** [comment]
+1 although is the count provided as a path or query parameter?

**Comment by stanleyxu2005** [comment]
@kkasravi What is `$uripath` stands for? Worker and master instances are not identified with a numeric id?

**Comment by kkasravi** [comment]
Actually no. WorkerId is the container id as implemented by @clockfly. I think it would be better if it could be a named property maybe something like 
DELETE /api/v1.0/supervisor/worker?workerId=<id> or
DELETE /api/v1.0/supervisor/worker?containerId=<id>

**Comment by stanleyxu2005** [comment]
It seems the set of apis are designed for Gearpump over YARN. I don't think the proposal makes the apis better if it does not used for standalone Gearpump. I'm going to close this issue, if nobody rejects.

**Comment by stanleyxu2005** [comment]
I'm quite satisfied with the solution of #1997
