### ISSUE TITLE
Define and isolate Admin UI

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1947]
admin operations like /terminate and worker, master, cgroup operations should be isolated and shown in separate UI panels. Angular components and JSON structures should be defined such that they can easily be isolated and possibly hosted in some like TAP

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
Current, in backend, there are three layer of users which require authentication.
1. guest
2. normal user
3. admin user.

We can only show authorized content when user is logged in as admin.

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-98
