### ISSUE TITLE
Need to support SSO (oauth2)

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1981]
Gearpump authentication should be expanded to support single-sign on. 
See https://intel-data.atlassian.net/browse/DPNG-5464.

**Comment by kkasravi** [comment]
@clockfly I think @karol-brejna-i either wanted these changes Monday 3/14 or for the next sprint. Let me know if you would like me to do this. There is a SSO document this is relevant that @TomaszT has.

**Comment by clockfly** [comment]
@karol-brejna-i 
 Where is the TAP OAUTH2 server? How can I register an app?

**Comment by clockfly** [comment]
@kkasravi  I think I can get the backbone code ready. I will try to make the OAUTH module pluggble, so that then we can develop a plugin for TAP OAuth Server.

**Comment by kkasravi** [comment]
@clockfly that would be great!

**Comment by karol-brejna-i** [comment]
@clockfly, TAP uses https://github.com/trustedanalytics/uaa 

Let me organize dev environment and send credentials to you on priv.

**Comment by clockfly** [comment]
@karol-brejna-i  Cool, can you help to apply an client id and client secret for us?

**Comment by karol-brejna-i** [comment]
Authentication works perfectly. Now, if TAP user tries to log in to Gearpump dashboard, he is allowed to do so.

The only outstanding thing is to restrict the access.

In TAP we can spawn a cluster in different organizations. Only users from given organization have access to the cluster in that org.

So, additional authorization step is required to validate if the user can access given cluster/dashboard (= is in given organization).

The broker would update dashboard configuration to remember the organization GUID for given cluster, and SSO plugin in dashboard would issue check request.


There is an endpoint in TAP (according to https://apidocs.cloudfoundry.org/232/organizations/retrieve_a_particular_organization.html) for checking that:
```GET /v2/organizations/<<some guid>>```

For example:
http://api.gearpump.gotapaas.eu/v2/organizations/0bc16bf2-bd80-4344-af6c-4de014b91064
