### ISSUE TITLE
Documentation related to akka-streams within the context of GearpumpMaterializer and other streaming frameworks

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1985]
- [ ] dataset transform comparisons 
- [ ] time window operations comparisons
- [ ] various examples comparisons
- [ ] deployment target comparisons
- [ ] connectors (source, sink) comparisons
- [ ] blueprints - partial graph composition, assembly

**Comment by kkasravi** [comment]
| Transforms  | akka-streams | flink | gearpump | beam |
|---|---|---|---|---|
| Aggregate |   |   |   |   |
| Cross |   |   |   |   |
| CoGroup |   |   |   |   |
| Distinct |   |   |   |   |
| Filter | | filter | filter |   |
| FlatMap | | flatMap | flatMap |   |
| Joins |   | join, leftOuterJoin, rightOuterJoin |   |   |
| Map | | map | map |   |
| Partitioning |   | custom, hash, map, range, sort  |   |   |
| Rebalance |   |   |   |   |
| Reduce |   |   |   |   |
| ReduceGroup |   |   |   |   |
| Union |   |   |   |   |

**Comment by darionyaphet** [comment]
@kkasravi should add compare with Apache Spark Streaming ? Although it's not a pure streaming processing framework :D

**Comment by kkasravi** [comment]
thanks @darionyaphet. Added spark streaming. Table(s) being assembled here will be used in a variety of contexts related to documentation, articles, etc.

**Comment by kkasravi** [comment]
This matrix will be replaced by apache beam's compatibility matrix and is superseded by https://issues.apache.org/jira/browse/GEARPUMP-22
