### ISSUE TITLE
Update documentation site

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1986]
- [ ] Update roadmap (out-of-date)
- [ ] Update use cases with small examples with code snippets
- [ ] Add an announcements tab or section - include new news
- [ ] Add twitter link
- [ ] Replace updated logo
- [ ] Update dashboard image

**Comment by darionyaphet** [comment]
Please update [gearpump version](http://www.gearpump.io/releases/latest/dev-rest-api.html#query-version)  from `0.7.1-SNAPSHOT` --> `0.7.6`

**Comment by kkasravi** [comment]
See https://issues.apache.org/jira/browse/GEARPUMP-28
