### ISSUE TITLE
display task location on dashboard

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1987]

**Comment by stanleyxu2005** [comment]
Can you be more specific what task to be shown in what way?

**Comment by manuzhang** [comment]
The scenario is when I find my task is running abnormally I need to access the log. I don't know, however, which executor log on which node I should look into so I have to check every of them.

**Comment by manuzhang** [comment]
@stanleyxu2005 It's not hard to get the location of `Task` from since we already have the task lists in `ExecutorSummary` for each executor.

```scala
  case class ExecutorSummary(
    id: Int,
    workerId: Int,
    actorPath: String,
    logFile: String,
    status: String,
    taskCount: Int,
    tasks: Map[ProcessorId, List[TaskId]],
    jvmName: String
  )
```

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-46
