### ISSUE TITLE
Add confirmation before doing irreversible operations

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#1989]
Propose to have a confirmation for irreversible operations, e.g. kill app restart app, so that we won't interrupt running applications by accidental click.

**Comment by stanleyxu2005** [comment]
![preview](https://cloud.githubusercontent.com/assets/5162687/13519874/775bfdae-e216-11e5-99a6-45ade955f84e.png)

**Comment by kkasravi** [comment]
Suggestion 
"Are you sure you want to kill the application?"

Ok  Cancel

**Comment by stanleyxu2005** [comment]
Updated
