### ISSUE TITLE
Cassandra integration

### ISSUE THREAD

**Issue by zapletal-martin** [gearpump/gearpump#1991]
This ticket will drive integration of Gearpump with Apache Cassandra database. I will outline a design approach as followup.

**Comment by darionyaphet** [comment]
`Apache Cassandra` is using `CQL` as a interface to access cluster .  Could merge this Cassandra driver into JDBC ?

**Comment by zapletal-martin** [comment]
Good question. I would think that's not possible though.

Firstly I can not find an up to date OS jdbc Cassandra driver. Secondly I think Gearpump may require some more lower level control. Something similar to https://github.com/datastax/spark-cassandra-connector may be needed. E.g. determining Cassandra cluster token ranges to be able to parallelize the source and achieve at least per-cassandra-partition ordering.

What do you think?

**Comment by darionyaphet** [comment]
More and more Storage System to support `SQL` as a standard interface to access data and a lot of developer are familiar with `SQL` and `JDBC` .  This can help them to access some system such as `PostgreSQL` ,`MySQL` ,`Cassandra` and `Phoenix`. But there are some difference between this systems we should try to make a good bridge between them .   :)

**Comment by zapletal-martin** [comment]
I definitely agree conceptually. SQL however only solves part of the problem - the actual query.

My understanding of the required approach is:

1) Get metadata about the requested table, especially partition key and clustering columns. These can be parameters of the source, but it should not be necessary.
2) Get metadata about cassandra token ranges. Each cassandra node is responsible for a subset (partition, shard) of the data
3) Given the parallelism defined for the source split the token ranges to available sources. In Cassandra Spark connector this is done using data locality. The addresses of the machines are known so if Cassandra runs on the same machines as Gearpump we could assign the closest node.
4) In each source query the rows from assigned token ranges. This is in my opinion where sql comes to play. If we use JDBC/SQL, Cassandra's Java driver or another library I do not know. I would think the Java driver is officially supported, up to date and mature. If you however have an architectural vision for shared approach between different sources we can take that into consideration.

Each cassandra partition is ordered by clustering column and therefore we can preserve the ordering. Ordering between partitions or partition keys is not maintained as is application specific.

**Comment by manuzhang** [comment]
@zapletal-martin we've migrating to https://issues.apache.org/jira/browse/GEARPUMP. Could you create a new jira there along with the above conversations ?

**Comment by manuzhang** [comment]
@zapletal-martin I've migrated this issue to https://issues.apache.org/jira/browse/GEARPUMP-91 and assigned it to you. Please continue to work with the community there.
