### ISSUE TITLE
gearpump enters Apache incubator 

### ISSUE THREAD

**Issue by darionyaphet** [gearpump/gearpump#2001]
I found a page at [incubator.apache.org/projects/gearpump.html](http://incubator.apache.org/projects/gearpump.html) and it seems gearpump will become a project under Apache Foundation . 

It's benefit to make gearpump more powerful and more popular . 

But  I don't know  if I have some pull request , should I commit to github ?

**Comment by kkasravi** [comment]
Hi @darionyaphet 

We will be moving our code over to https://github.com/apache/incubator-gearpump. This repo isn't active yet and will be based on a SHA (github commit id) we give apache. Then there will be a JIRA and PR process just like other ASF projects. We'll let you know - should happen in the next few days, possibly longer.

**Comment by clockfly** [comment]
@darionyaphet 

1. We will still use github pull request to manage contributations after Apache incubation.
2. For now, you can just submit PR as usual, nothing changes from contributors' side.

After we convert the code to https://github.com/apache/incubator-gearpump, then we will need the contributators to submit PR to this new repo.

**Comment by darionyaphet** [comment]
@kkasravi @clockfly [issues-GEARPUMP](https://issues.apache.org/jira/browse/GEARPUMP/) have created . :congratulations:

**Comment by stanleyxu2005** [comment]
According to other projects experience, the github repo will remove "issues" and "pr" tabs and migrate open issues to JIRA system.
