### ISSUE TITLE
Dashboard login jump failed

### ISSUE THREAD

**Issue by darionyaphet** [gearpump/gearpump#2010]
I checkout `gearpump-0.7.6` and running `sbt clean +assembly +packArchiveZip ` to building a released package and  then I startup the `Gearpump service` in Local Mode . Using `bin/local` to start cluster and `bin/services` to start Web Service . But when I open `http://127.0.0.1:8090` in browser try to login it (the username and password is default , admin:admin ) , it could't jump to cluster page and stay in login page . I think maybe something wrong but I can't found anything in log .

**Comment by clockfly** [comment]
@darionyaphet 

Have you tried using the chrome developer tool to record the network traffic?

**Comment by stanleyxu2005** [comment]
Please post any errors of browser's console

**Comment by darionyaphet** [comment]
@clockfly @stanleyxu2005 thank you for you help ~ 

I open chrome's `developer tool` and found a 401 Error

```
POST http://127.0.0.1:8090/logout 401 (Unauthorized)  jquery.js:9172
l.cors.b.crossDomain.send @ jquery.js:9172
n.extend.ajax @ jquery.js:8653
n.(anonymous function) @ jquery.js:8804
logout @ login.js:37
(anonymous function) @ login.js:42
i @ jquery.js:3182
j.fireWith @ jquery.js:3312
n.extend.ready @ jquery.js:3531
J @ jquery.js:3547
```

**Comment by darionyaphet** [comment]
I'm not sure login is really needed . Maybe we can display a default page to show basic cluster status and make user login when want to submit a new job .

**Comment by stanleyxu2005** [comment]
@darionyaphet You can deploy a cluster with login feature disabled. The switch is in config file.

**Comment by darionyaphet** [comment]
Yes set `authentication-enabled ` to `false` will skip login module :+1:

**Comment by karol-brejna-i** [comment]
@darionyaphet do you think we could close this?
It seems simplification of login is being addressed in https://github.com/gearpump/gearpump/issues/2021 ...

**Comment by darionyaphet** [comment]
It seem have found the problem   I will close it :)
