### ISSUE TITLE
Fix code style by following https://github.com/databricks/scala-style-guide

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#2011]
For us, https://github.com/databricks/scala-style-guide is a more suitable code style.

We should refactor our code to follow this style.

**Comment by manuzhang** [comment]
we may use [scalariform](https://github.com/sbt/sbt-scalariform) to enforce some of them.

**Comment by kkasravi** [comment]
See [GEARPUMP-11](https://issues.apache.org/jira/browse/GEARPUMP-11)
