### ISSUE TITLE
GS-collections rename to eclipse-collections

### ISSUE THREAD

**Issue by darionyaphet** [gearpump/gearpump#2027]
I found `gearpump` is using `gearpump-shaded-gs-collections` to improvment `TaskActor` memory usage . Current `gs-collections` have contributed to Eclipse Foundation and rename to `eclipse-collections` . Could use `org.eclipse.collections:eclipse-collections:7.0.2`  to replace origin one ?

**Comment by clockfly** [comment]
@darionyaphet 

Sorry for the late response. We will only considering updating the dependency library when there are explicit **performance reason** or other **obvious reasons**.

Have you see problems of current gearpump-shaded-gs-collections version that worth upgrading?

**Comment by darionyaphet** [comment]
@clockfly I test `gs-collections 6.2.0` and `eclipse 7.0.2` memory usage and time usage . They are the same . Maybe don't need to upgrade :P
