### ISSUE TITLE
Testing App with GearPump Dependencies 

### ISSUE THREAD

**Issue by kolobok01** [gearpump/gearpump#2034]
Testing and app with core and streaming. What Dependencies should i include in the project to get access to Masterharness and MiniCluster classes. ?

**Comment by clockfly** [comment]
@kolobok01 

Masterharness and MiniCluster belongs to test code, which are NOT published to maven.

If you want to test Gearpump in IDE, you can use "EmbededCluster", which create a in-process cluster. 

Here is an example: 
https://github.com/gearpump/gearpump/blob/master/examples/streaming/wordcount/src/main/scala/io/gearpump/streaming/examples/wordcount/WordCount.scala

And java version:
https://github.com/gearpump/gearpump/blob/master/examples/streaming/wordcount-java/src/main/java/io/gearpump/streaming/examples/wordcountjava/WordCount.java

**Comment by kolobok01** [comment]
Awsome but  io.gearpump.cluster.embedded.EmbeddedCluster is in deamon is it getting packaged into core or is it a separate import ?

**Comment by clockfly** [comment]
@kolobok01 

Thanks! This is a real issue, daemon artifact are not published also. 

As a work-around, you can use the snapshot build temporary
https://oss.sonatype.org/content/repositories/snapshots/com/github/intel-hadoop/gearpump-daemon_2.11/0.8.1-SNAPSHOT/

```
Snapshot Repo URL:https://oss.sonatype.org/content/repositories/snapshots
com.github.intel-hadoop %% gearpump-daemon % 0.8.1-SNAPSHOT
```
Would you mind cross-posting this issue to https://issues.apache.org/jira/browse/GEARPUMP? We'll get it fixed in 0.8.1

**Comment by kolobok01** [comment]
Added Jira. 
https://issues.apache.org/jira/browse/GEARPUMP-29

>  Gearpump provides pretty awesome test utils for testing. Like Masterharness and MiniCluster. It would be great if test suit artifact was published as separate dependency, as well as daemon artifact are not published also.

>

**Comment by manuzhang** [comment]
closed this issue as it has been moved to jira
