### ISSUE TITLE
Documents / Future of Project

### ISSUE THREAD

**Issue by morganhferry** [gearpump/gearpump#2141]
There seems to be no working link for documentation and searching online yields none. The Incubator at Apache is retired, and the documentation page and all other pages have been removed.

Is anyone aware of the future of the project, whether it will continue to receive support? Will it eventually be placed into apache officially?

**Comment by manuzhang** [comment]
Sorry, I haven't got time to set up the documentation website. Hopefully, I can get it done this week. I'll continue to maintain the project and offer support as possible. As for the future, I'm not sure myself and it's unlikely for Gearpump to be placed into Apache. Feel free to email me (owenzhang1990@gmail.com) to share your thoughts or for any questions.

**Comment by morganhferry** [comment]
Thanks! We would love the documentation. We are trying to move forward with implementation and would love to help. We need to get our hands on some additional source code so we can upgrade them to work with newer products. IE: The gearpump-external-kafka package is coded against a much older version of Kafka than the current. We would like to upgrade it to the current so we can utilize newer functionality. Where can we locate this code? As well as other packages, such as gearpump-streaming.

**Comment by morganhferry** [comment]
Ah sorry, I found it.

**Comment by manuzhang** [comment]
Thanks, the repo is at https://github.com/gearpump/gearpump-externals

**Comment by manuzhang** [comment]
@morganhferry The docs are up at https://gearpump.github.io/gearpump/

**Comment by morganhferry** [comment]
Thanks!
