### ISSUE TITLE
Extend Appmaster to be aware of data locality when creating tasks

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#369]
this appmaster should be able to collocate the task (KafkaSource) with the TopicAndPartition it will pull from.

**Comment by clockfly** [comment]
It is important, please have a design for this.

**Comment by clockfly** [comment]
Maybe do this by adding a plugin point for task scheduling.

**Comment by clockfly** [comment]
Hi huafeng,

Please also fix the comments leaved in https://github.com/intel-hadoop/gearpump/pull/403

https://github.com/intel-hadoop/gearpump/pull/403#issuecomment-73821227

https://github.com/intel-hadoop/gearpump/pull/403#discussion_r24468748

**Comment by manuzhang** [comment]
@clockfly @huafengw 
I think the executor states should be external to TaskScheduler, who is able to schedule resources for tasks given the DAG and worker info. `executorToTaskIds` states could be kept by TaskManager and on executor failure, TaskManager would know which tasks need reschedule and ask TaskScheduler to do so. Hence, there would be no difference between task failure and executor failure for TaskScheduler when rescheduling. That would make TaskScheduler interface cleaner and more extendable.

**Comment by manuzhang** [comment]
@huafengw are you still working on this ?

**Comment by huafengw** [comment]
Haven't update for a long time. I will migrate this one to Apache jira.

**Comment by manuzhang** [comment]
moved to https://issues.apache.org/jira/browse/GEARPUMP-49
