### ISSUE TITLE
Frontend requires a javascript graph API

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#491]
In addition to the JSON model that is visualized by the visdag widget, we should also have a javascript graph api so adding, deleting nodes, defining new edges, etc.

**Comment by kkasravi** [comment]
One candidate is cytoscape which does visualization and provides a graph api. We already have visualization using vis.js, however we should look at the Graph API. See http://js.cytoscape.org/

**Comment by clockfly** [comment]
@kkasravi 

There is a nice demo in visjs. 
http://visjs.org/examples/network/21_data_manipulation.html

Maybe we can just follow its approach.

**Comment by kkasravi** [comment]
Yes, this is nice. We will need the related REST/WS API to send the DAG.

**Comment by clockfly** [comment]
Yes, I agree.

This issue should be solved together with https://github.com/intel-hadoop/gearpump/issues/53

**Comment by clockfly** [comment]
In this feature, we can allow user to compose a DAG completely in UI.

**Comment by huafengw** [comment]
A json example of SubmitApplicationRequest:
```
{
  "appName": "complexdag",
  "processors": [
    [
      0,
      {
        "id": 0,
        "taskClass": "A",
        "parallelism": 1,
        "description": "processor A",
        "jar": {
          "name": "file1",
          "filePath": {
            "path": "path1"
          }
        }
      }
    ],
    [
      1,
      {
        "id": 1,
        "taskClass": "B",
        "parallelism": 1,
        "description": "processor B",
        "jar": {
          "name": "file2",
          "filePath": {
            "path": "path3"
          }
        }
      }
    ],
    [
      2,
      {
        "id": 2,
        "taskClass": "C",
        "parallelism": 1,
        "description": "processor C",
        "jar": {
          "name": "file3",
          "filePath": {
            "path": "path3"
          }
        }
      }
    ]
  ],
  "dag": {
    "vertexList": [
      0,
      1,
      2
    ],
    "edgeList": [
      [
        1,
        "io.gearpump.partitioner.ShufflePartitioner",
        2
      ],
      [
        0,
        "io.gearpump.partitioner.HashPartitioner",
        1
      ]
    ]
  },
  "userconfig": {
    "_config": {
      "key1": "value1"
    }
  }
}
```

**Comment by stanleyxu2005** [comment]
The PR #1452 is ready. Here are some screenshots.

![1_how_to_enter_compose_view](https://cloud.githubusercontent.com/assets/5162687/10188694/125d37b2-6794-11e5-8920-9aff2b829ca6.png)
Pic 1: Enter compose DAG ui

![2_click_to_add_processor](https://cloud.githubusercontent.com/assets/5162687/10188697/1692f560-6794-11e5-9a4a-a53ea4f941be.png)
Pic 2: Click to add processor

![3_add_processor_dialog_with_validation](https://cloud.githubusercontent.com/assets/5162687/10188704/1c96ac5e-6794-11e5-95c1-4ab940e0a9e1.png)
Pic 3: Add/modify processor (has validation)

![4_add_edge_dialog_with_validation](https://cloud.githubusercontent.com/assets/5162687/10188706/2163da4a-6794-11e5-81e9-5fb62d6d63a5.png)
Pic 4: Add/modify edge (has validation)

![5_drag_or_use_dialog_to_add_jar_files](https://cloud.githubusercontent.com/assets/5162687/10188713/261056c2-6794-11e5-8d6c-c6b02f3e54ba.png)
Pic 5: Drag and drop zone for adding jar files (you can also click the zone to open a dialog)

![6_use_contextmenu_to_modify_or_delete_element](https://cloud.githubusercontent.com/assets/5162687/10188715/2c3806da-6794-11e5-95ca-12336683f5ee.png)
Pic 6: Use context menu to remove/modify element

![7_when_done_show_view_application_button](https://cloud.githubusercontent.com/assets/5162687/10188721/3186f47a-6794-11e5-9986-e93dafcaff1c.png)
Pic 7: After submitting is done, show a "View application" button.
