### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#606]
We need to define the requirements and apply them to implementable wireframes for UI. 

##### Structure
Here is the sitemap:
- Dashboard 
- Cluster
  - Master
  - Workers
  - Configuration
- Applications
  - Overview
  - Application Detail
    - Summary
    - Processors
    - Tasks
    - Configuration
- Tool
- Administration

##### Dashboard 
A place to look at the overall cluster and application status

##### Cluster
The section is used to view and manage the cluster. It consists of three parts as follows.

##### Master
Master is the brain of the cluster. It can be one master or a master group. We need to:
- View current runtime information
- View current resource usage information
- View log and config files
- View recent warning and failure alerts (parsed from log) as a list
- View recent resource usage in charts

###### Wireframe (in 6-6 column layout)
![master](https://cloud.githubusercontent.com/assets/146453/6641492/4b93cd66-c95b-11e4-90b5-d8567928b54f.jpg)

1. On top left, the summary box lists master’s runtime information. *Equivalent to the existing master page*
2. Below, the alerts box lists recent warnings and errors. Alerts are sorted by timestamp.
3. On top right, there are two circles. The first circle indicates the number of worker instances. The second circle indicates the usage of slots. 
4. Below, there will be couple of line charts (e.g. number of errors) to indicate the cluster running status in a particular past period.

##### Workers
Worker instances are a set of computation resources. We need to:
- View current runtime information
- View current resource usage information (optional)
- View aggregated resource usage information
- View individual worker instance details

###### Wireframe
![workers](https://cloud.githubusercontent.com/assets/146453/6641519/74b0ec92-c95b-11e4-92de-c6494dc6777d.jpg)
1. On top there is a fuzzy filter to identify worker instance (optional)
2. Below there is a table of worker instances. (Pagination control is optional) 

##### Worker "X" Detail
Worker is running on a specified physical machine. Worker can created a set of executors to run particular applications. When applications are stopped, executors will be destroyed. And the worker will become idle. We need to:
- View the current runtime information of worker
- View the current executors' activities
- View recent warning and failure alerts (parsed from log) as a list
- View recent resource usage in charts

###### Wireframe (in 6-6 column layout)
![workerx](https://cloud.githubusercontent.com/assets/146453/6641525/7d257438-c95b-11e4-82b5-8e940ed8dc0a.jpg)

1. On top left, the Summary box lists the information of the worker.
2. Below, there is a list of executors with corresponding actorpath, etc.
3. Below, the alerts box lists recent warnings and errors. Alerts are sorted by timestamp.
4. On the right side there will be couple of charts, e.g. CPU time, Memory usage, Disk IO, Network IO.

##### Configuration
We need to:
- View cluster's configuration
- Download config file
- Modify and provisioning configuration changes (Not in scope)
- View configuration change history (Not in scope)

###### Wireframe
![apps_config](https://cloud.githubusercontent.com/assets/146453/6641607/fe9f76ee-c95b-11e4-8fd4-590221ec2ea5.jpg)

##### Applications
The section is used to view and manage the applications. It consists of three parts as follows.

##### Submit New Application
Not implemented yet. It will be a wizard to submit new application.

##### Application Overview
We need to:
- View all running or completed applications as a list

###### Wireframe
![apps](https://cloud.githubusercontent.com/assets/146453/6641551/abfe4352-c95b-11e4-9292-32c28db6ddb9.jpg)

1. On top there is a fuzzy filter
2. Right to filter there is a button to submit a new application (Not in scope)
3. Below there is a table of applications.

##### App "X" Detail
Detail will be broken down into four parts: Summary, Processors, Tasks, Configuration.

##### App "X" Summary
This is the overview of a running application. We need to:
- View current runtime information
- View important message processing metrics
- View recent resource usage in charts

###### Wireframe (in 6-6 column layout)
![appx](https://cloud.githubusercontent.com/assets/146453/6641583/dd348cba-c95b-11e4-8c5b-3047bd70bab2.jpg)

1. On top left there is a summary box.
2. Below there is a list of important message processing metrics (1min, 10min, 1hour, etc.)
3. On top right, there is a button back to Applications overview page
4. On the right side there are couple of line charts (throughput, processing time, latency at application level)

##### App "X" Processors (Type: streaming application)
Application can be described as a DAG. Nodes are processors. Edge between two nodes describes how data flow goes and its throughput, etc. We need to:
- View the topology of the processors (DAG control). 
- View the current throughput, working load, etc. on the DAG live.
- The DAG control should support add/modify/remove nodes/edges live with context menu.
- View the metrics data of every single processors

###### Wireframe (in 6-6 column layout)
![apps_processes](https://cloud.githubusercontent.com/assets/146453/6641594/ef66ee14-c95b-11e4-9bbb-1e6473aa6454.jpg)

1. On top left there is a DAG control. Above the DAG control, the number of processed messages should be shown.
2. Below there is a selector for different metrics with a table of metrics data (the table can be moved to right, if we want to bind the table with dag when hovering over a row or a dag node)
3. On top right, there is a button back to Applications overview page
4. On the right side there are charts of different metrics 

##### App "X" Tasks (When user click one processor of DAG)
Tasks describe the internal relationship of a processor. We need to:
- View the details of tasks.
- View the metrics of tasks.
- Allow user to add/remove tasks to adjust processors work performance. (Not in scope)

###### Wireframe (in 6-6 column layout)
![apps_tasks](https://cloud.githubusercontent.com/assets/146453/6641604/fa636644-c95b-11e4-931c-f821e45b1ef4.jpg)

1. On top left there is a pie chart of tasks’ throughput.
2. Below there is table of tasks information
3. On top right, there is a button back to Applications overview page
4. On the right side there are charts of metrics at task level

##### App "X" Configuration
Configuration of the application. Similar to Cluster's configuration.

**Comment by clockfly** [comment]
Looks good.

The DAG should be in APP page?

**Comment by clockfly** [comment]
Remain tasks:

1. add jvm metrics.
2. add time bar for metrics.
3. add executor detail metrics.
4. add error bar.
