### ISSUE TITLE
allow multiple output streams for a processor

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump#730]
Our current model is: all subscriptions will receive the message. Inside each subscription, one task actor will receive.

It is better if we can support use case like: one task actor can generate multiple output streams.
For example, for IoT data flow in, if the data exceeds some threshold, generate alert message to one stream (subscription), otherwise generate data to a normal stream (subscription).

**Comment by whjiang** [comment]
Sean mentioned this case can be solved with filters.
```
val stream = streamApp.newStream(input).process[Either(A, B)](processor)
val normalOut = stream.filter(_.left)
val alerts = stream.filter(_.right)
```

I am not sure whether it can solve all cases and other languages like Java or not.

**Comment by kkasravi** [comment]
I think in both Tez and Flink they have the ability to broadcast and even lookup and message a particular task. Having the knowledge of downstream tasks and/or the ability to output some messages to specific downstream tasks could be valuable. At the same time in a pub/sub model the publisher should not be aware of subscribers. One strength of the current model is its very simple.

**Comment by whjiang** [comment]
duplicated by #1456.
