### ISSUE TITLE
Project size is becoming difficult for intellij to handle

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#839]
Whenever I switch branches intellij will detect and often refreshes the sbt build. This causes a full recomplication and effectively renders intellij almost useless for several minutes. Intellij reports 20+ processes running.

**Comment by clockfly** [comment]
What is your suggestion?

**Comment by kkasravi** [comment]
We should upgrade to 0.13.8. I think it has a number of improvements
[excludeDependencies](https://github.com/sbt/sbt/pull/1748)
[incrementalCompiler](https://github.com/sbt/sbt/pull/1714 Expose mechanism whereby bytecode enhancement can be run *before* saving incremental compiler hashes.)

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
Seems 0.13.8 cannot solve the problem here. 

We already moved some project outside of Gearpump. 
Close this for now.
