### ISSUE TITLE
track serialization / deserialization latency and display on dashboard

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#870]
as serde may affect overall performance significantly

**Comment by kkasravi** [comment]
See #875. We should also include serde info if possible as part of #875.

**Comment by stanleyxu2005** [comment]
@manuzhang Where can I find serde related metrics in restapi response?

**Comment by huafengw** [comment]
we do not have these metrics now

**Comment by stanleyxu2005** [comment]
So I change the label to module core.

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-46
