### ISSUE TITLE
Provide summary path information for any two points selected in the DAG

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#875]
It would be valuable to see metrics like total average latency, total message throughput along an arbitrary path within the DAG. I could envision this working similar to double clicking on a given processor but instead the user can select one processor and then the second processor. This will then highlight in some different color all paths from that one processor to the second processor. Selecting a highlighted path will then open a tab that shows summary metrics for that pathway. Selecting a source processor and sink processor and then a highlighted path will allow the user to easily see summary metrics for the entire processing pathway.

**Comment by kkasravi** [comment]
Stanley it may make sense to have a JS Graph (or scala.js) that will do things like find all outgoing, incoming edges within a DAG given a vertex rather than trying to get this info from the server. However, it will likely still require a new REST/WS call that can fetch metrics along a given path continuously.

**Comment by kkasravi** [comment]
Currently the JS object StreamingDag has the following API (where _* methods have been excluded)
```
StreamingDag {
  updateMetricsArray([])
  updateMetrics(name,data)
  hasMetrics
  getNumOfTasks
  getProcessorsData
  getEdgesData
  calculateProcessorConnections
  getReceivedMessages
  getSentMessages
  getProcessingTime
  getReceiveLatency
  hierarchyDepth
}
```
StreamingDag.calculateProcessorConnections is the closest API available that would provide incoming and outgoing edges for a given processor and may be sufficient. 
The graph below shows the user selecting two nodes: Source_0 and Sink_3
![screen shot 2015-04-24 at 7 35 56 am](https://cloud.githubusercontent.com/assets/146453/7321004/aaaa6e08-ea54-11e4-8680-6868531bb790.png)

After selecting the 2nd node, all paths connecting the 2 are hightlighted as show below 

![screen shot 2015-04-24 at 7 40 40 am](https://cloud.githubusercontent.com/assets/146453/7321124/4db4ee34-ea55-11e4-98d3-8c3d50117796.png)

Selecting one of these paths would then show metrics (throughput, latency) for that path

![screen shot 2015-04-24 at 7 44 47 am](https://cloud.githubusercontent.com/assets/146453/7321213/d0286dd2-ea55-11e4-9875-1e1b9a32319d.png)

**Comment by stanleyxu2005** [comment]
* [ ] If a processor has stalling tasks, all edges on the path to its sink processor should also be marked with red.
* [ ] Mark the critical path(s) with different color (or style) by default.
* [ ] When clicking a node, all its metrics will be shown in a hover card.

**Comment by stanleyxu2005** [comment]
Here is a preview of default DAG view with critical path marked. Colors might be revised later. If you guys have any good recommendation, it would be great to share with me.
![untitled](https://cloud.githubusercontent.com/assets/5162687/13663726/311b86f8-e6de-11e5-92b0-86c13f882103.png)

**Comment by kkasravi** [comment]
The graph looks great, would be great to see a demo implementation.

**Comment by kkasravi** [comment]
This has been moved to https://issues.apache.org/jira/browse/GEARPUMP-46.
