### ISSUE TITLE
Storm WordCount cannot run correctly on gearpump

### ISSUE THREAD

**Issue by skw1992** [gearpump/gearpump#924]
The value of "SINK PROCESSORS RECEIVE THROUGHPUT" is always 0 msgs/s.

**Comment by manuzhang** [comment]
Note that Storm WordCount example has a ShellBolt which invokes a python subprocess. I'll look into it.

**Comment by manuzhang** [comment]
I found deadlocks reported in https://issues.apache.org/jira/browse/STORM-75 which was fixed after Storm-0.9.3

**Comment by huafengw** [comment]
Wrong pull request reference, reopen the issue.

**Comment by stanleyxu2005** [comment]
Do we have a regression test or normal test to cover this?
