### ISSUE TITLE
Compare various frameworks with Gearpump

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#985]
[Story](https://www.pivotaltracker.com/story/show/96047698)
Provide presos/decks that compare other frameworks with GearPump

**Comment by clockfly** [comment]
Items:

- [ ] Compare Heron with GearPump
- [ ] Compare Flink with GearPump
- [ ] Compare akka-streams with GearPump
- [ ] Compare DataTorrent with GearPump

**Comment by kkasravi** [comment]
We have a comparison matrix in https://www.dropbox.com/s/1s8pnjwgkkvik4v/GearPump%20Edge%20Topologies%20and%20Deployment.pptx?dl=0

**Comment by manuzhang** [comment]
@kkasravi Is there a way to co-edit this matrix as all the frameworks are evolving and I find some items are no longer true ?

**Comment by kkasravi** [comment]
this has been largely replaced by the akka-streams and apache beam efforts
